import React, { createContext, useContext, useState, useEffect } from 'react';

export const LANGUAGES = [
  // --- Indian Languages ---
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', region: 'India', flag: '🇮🇳', category: 'indian' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', region: 'India / WB', flag: '🇮🇳', category: 'indian' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', region: 'India / MH', flag: '🇮🇳', category: 'indian' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', region: 'India / AP & TS', flag: '🇮🇳', category: 'indian' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', region: 'India / TN', flag: '🇮🇳', category: 'indian' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', region: 'India / GJ', flag: '🇮🇳', category: 'indian' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', region: 'India / KA', flag: '🇮🇳', category: 'indian' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', region: 'India / KL', flag: '🇮🇳', category: 'indian' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', region: 'India / PB', flag: '🇮🇳', category: 'indian' },
  { code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ', region: 'India / OD', flag: '🇮🇳', category: 'indian' },
  { code: 'as', name: 'Assamese', nativeName: 'অসমীয়া', region: 'India / AS', flag: '🇮🇳', category: 'indian' },
  { code: 'ur', name: 'Urdu', nativeName: 'اردو', region: 'India / South Asia', flag: '🇮🇳', category: 'indian' },

  // --- International Languages ---
  { code: 'en', name: 'English', nativeName: 'English (US)', region: 'Global', flag: '🇺🇸', category: 'international' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', region: 'Spain / LatAm', flag: '🇪🇸', category: 'international' },
  { code: 'fr', name: 'French', nativeName: 'Français', region: 'France', flag: '🇫🇷', category: 'international' },
  { code: 'de', name: 'German', nativeName: 'Deutsch', region: 'Germany', flag: '🇩🇪', category: 'international' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語', region: 'Japan', flag: '🇯🇵', category: 'international' },
  { code: 'zh', name: 'Chinese', nativeName: '中文 (简体)', region: 'China', flag: '🇨🇳', category: 'international' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', region: 'Middle East', flag: '🇸🇦', category: 'international' },
  { code: 'ru', name: 'Russian', nativeName: 'Русский', region: 'Russia', flag: '🇷🇺', category: 'international' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português', region: 'Brazil / Portugal', flag: '🇧🇷', category: 'international' },
  { code: 'ko', name: 'Korean', nativeName: '한국어', region: 'South Korea', flag: '🇰🇷', category: 'international' },
  { code: 'it', name: 'Italian', nativeName: 'Italiano', region: 'Italy', flag: '🇮🇹', category: 'international' },
];

export const TRANSLATIONS = {
  en: {
    // Nav & Brand
    aiRadar: 'AI SaaS Radar',
    radarActive: 'Radar Active',
    offline: 'Offline',
    searchPlaceholder: 'Search incidents, anomalies, IPs, users...',
    simulateAttack: 'Simulate Attack',
    notifications: 'Notifications',
    liveNotifLog: 'Live Notification Log',
    clearAll: 'Clear all',
    noNotif: 'No new notifications',
    teamName: 'WolfPack Squadron',
    hackName: 'NexHack 2.0',
    selectLanguage: 'Select Language',
    searchLanguage: 'Search language or country...',
    indianLanguages: 'Indian Languages',
    internationalLanguages: 'International',

    // Sidebar
    navDashboard: 'Dashboard',
    navThreatAlerts: 'Threat Radar',
    navTraffic: 'Traffic Analytics',
    navWhatsApp: 'WhatsApp Dispatch',
    navSimulator: 'Attack Simulator',
    navAuditLogs: 'Audit Logs',
    navSettings: 'Engine Settings',

    // Metrics Grid
    metricTotalEvents: 'Total Ingestion Events',
    metricEventsSub: 'Real-time sliding window telemetry',
    metricAnomalies: 'Anomalies Flagged',
    metricAnomaliesSub: 'Heuristic + spike triggers',
    metricThreatLevel: 'Active Threat Level',
    metricThreatLevelSub: 'Dynamic baseline assessment',
    metricWhatsApp: 'Autonomous WhatsApp Dispatches',
    metricWhatsAppSub: 'Zero-jargon alerts transmitted',
    statusNominal: 'Telemetry Nominal',
    statusIncidents: 'Critical Incidents',
    statusStrict: 'Strict Shield',
    statusDispatched: 'Instant Alerts',

    // Traffic Chart
    chartTitle: 'Live Telemetry Ingestion vs Anomaly Bursts',
    chartSub: 'Real-time sliding window event volume with heuristic anomaly spikes',
    chartLegendIngestion: 'Ingestion (eps)',
    chartLegendAnomalies: 'Anomalies (count)',
    tab15m: '15 Mins',
    tab1h: '1 Hour',
    tab24h: '24 Hours',
    filterAll: 'All Traffic',
    filterAnomalies: 'Anomalies Only',
    statPeakRate: 'Peak Ingestion Rate',
    statAnomalyRate: 'Real-time Anomaly Rate',
    statWindow: 'Window Duration',
    statBaseline: 'Baseline Status',
    baselineStable: 'STABLE (12s)',

    // Threat Feed
    feedTitle: 'Real-Time Threat Intelligence & Zero-Jargon Synthesis',
    feedSub: 'Autonomous sliding-window telemetry radar with instant natural language translation',
    feedLiveActive: 'LIVE STREAM ACTIVE',
    filterAllAlerts: 'All Alerts',
    filterActive: 'Active',
    filterCritical: 'Critical',
    filterResolved: 'Resolved',
    noAlertsFound: 'No incidents match your search query.',
    takeRemediation: 'Take Remediation Action',
    actionCompleted: 'Incident Resolved & Protected',
    showTelemetry: 'Show Raw Telemetry',
    hideTelemetry: 'Hide Raw Telemetry',
    dispatchedToWhatsApp: 'Dispatched to WhatsApp',
    dispatchedTo: 'Dispatched to',

    // Hero Card
    heroBadge: 'ZERO-JARGON RADAR',
    heroTitle: 'Autonomous WhatsApp Threat Pipeline',
    heroSub: 'When the heuristic sliding-window flags an anomaly, our engine crafts plain-English zero-jargon mobile alerts and transmits them instantly to operators via WhatsApp API.',
    heroActiveRecipient: 'Active Recipient:',
    heroBtnTest: 'Test WhatsApp Dispatch',
    heroBtnSim: 'Trigger Simulator',

    // General
    languageChangedToast: 'Language changed to',
    saveChanges: 'Save Changes',
    cancel: 'Cancel',
    close: 'Close',
  },
  hi: {
    // Nav & Brand
    aiRadar: 'एआई सा SaaS रडार',
    radarActive: 'रडार सक्रिय है',
    offline: 'ऑफ़लाइन',
    searchPlaceholder: 'घटनाएं, विसंगतियां, आईपी, उपयोगकर्ता खोजें...',
    simulateAttack: 'हमले का अनुकरण करें',
    notifications: 'सूचनाएं',
    liveNotifLog: 'लाइव सूचना लॉग',
    clearAll: 'सभी हटाएं',
    noNotif: 'कोई नई सूचना नहीं है',
    teamName: 'वुल्फपैक स्क्वाड्रन',
    hackName: 'नेक्सहैक 2.0',
    selectLanguage: 'भाषा चुनें',
    searchLanguage: 'भाषा या देश खोजें...',
    indianLanguages: 'भारतीय भाषाएं',
    internationalLanguages: 'अंतर्राष्ट्रीय भाषाएं',

    // Sidebar
    navDashboard: 'डैशबोर्ड',
    navThreatAlerts: 'खतरा रडार',
    navTraffic: 'ट्रैफ़िक विश्लेषण',
    navWhatsApp: 'व्हाट्सएप प्रेषण',
    navSimulator: 'हमला सिम्युलेटर',
    navAuditLogs: 'ऑडिट लॉग',
    navSettings: 'इंजन सेटिंग्स',

    // Metrics Grid
    metricTotalEvents: 'कुल इनपुट घटनाएं',
    metricEventsSub: 'रियल-टाइम स्लाइडिंग विंडो टेलीमेट्री',
    metricAnomalies: 'पहचानी गई विसंगतियां',
    metricAnomaliesSub: 'ह्यूरिस्टिक + स्पाइक ट्रिगर्स',
    metricThreatLevel: 'सक्रिय खतरे का स्तर',
    metricThreatLevelSub: 'गतिशील बेसलाइन मूल्यांकन',
    metricWhatsApp: 'स्वायत्त व्हाट्सएप प्रेषण',
    metricWhatsAppSub: 'आसान भाषा में त्वरित मोबाइल अलर्ट',
    statusNominal: 'टेलीमेट्री सामान्य',
    statusIncidents: 'गंभीर घटनाएं',
    statusStrict: 'सुरक्षा कवच सक्रिय',
    statusDispatched: 'त्वरित अलर्ट',

    // Traffic Chart
    chartTitle: 'लाइव टेलीमेट्री इनपुट बनाम विसंगति स्पाइक्स',
    chartSub: 'ह्यूरिस्टिक विसंगतियों के साथ रियल-टाइम स्लाइडिंग विंडो इवेंट वॉल्यूम',
    chartLegendIngestion: 'इन्जेशन दर (eps)',
    chartLegendAnomalies: 'विसंगति गणना',
    tab15m: '15 मिनट',
    tab1h: '1 घंटा',
    tab24h: '24 घंटे',
    filterAll: 'सम्पूर्ण ट्रैफ़िक',
    filterAnomalies: 'केवल विसंगतियां',
    statPeakRate: 'अधिकतम इनपुट दर',
    statAnomalyRate: 'रियल-टाइम विसंगति दर',
    statWindow: 'विंडो अवधि',
    statBaseline: 'बेसलाइन स्थिति',
    baselineStable: 'स्थिर (12s)',

    // Threat Feed
    feedTitle: 'रियल-टाइम थ्रेट इंटेलिजेंस एवं सरल भाषा विश्लेषण',
    feedSub: 'त्वरित सरल भाषा अनुवाद के साथ स्वायत्त स्लाइडिंग-विंडो टेलीमेट्री रडार',
    feedLiveActive: 'लाइव स्ट्रीम सक्रिय',
    filterAllAlerts: 'सभी अलर्ट',
    filterActive: 'सक्रिय',
    filterCritical: 'अति-गंभीर',
    filterResolved: 'समाधान हुआ',
    noAlertsFound: 'आपकी खोज के अनुसार कोई घटना नहीं मिली।',
    takeRemediation: 'सुरक्षा कार्रवाई करें',
    actionCompleted: 'घटना का समाधान हुआ एवं सुरक्षित',
    showTelemetry: 'रॉ टेलीमेट्री देखें',
    hideTelemetry: 'रॉ टेलीमेट्री छिपाएं',
    dispatchedToWhatsApp: 'व्हाट्सएप पर भेजा गया',
    dispatchedTo: 'को भेजा गया',

    // Hero Card
    heroBadge: 'सरल भाषा रडार',
    heroTitle: 'स्वायत्त व्हाट्सएप सुरक्षा पाइपलाइन',
    heroSub: 'जब हमारा स्लाइडिंग-विंडो किसी विसंगति को पहचानता है, तो इंजन सरल बिना-तकनीकी-जटिलता वाला मोबाइल अलर्ट तैयार करता है और तुरंत व्हाट्सएप एपीआई के माध्यम से प्रेषित करता है।',
    heroActiveRecipient: 'सक्रिय प्राप्तकर्ता:',
    heroBtnTest: 'व्हाट्सएप परीक्षण करें',
    heroBtnSim: 'सिम्युलेटर शुरू करें',

    // General
    languageChangedToast: 'भाषा बदलकर की गई:',
    saveChanges: 'परिवर्तन सहेजें',
    cancel: 'रद्द करें',
    close: 'बंद करें',
  },
  bn: {
    // Nav & Brand
    aiRadar: 'এআই সা SaaS রাডার',
    radarActive: 'রাডার সক্রিয়',
    offline: 'অফলাইন',
    searchPlaceholder: 'ঘটনা, অসঙ্গতি, আইপি, ব্যবহারকারী অনুসন্ধান...',
    simulateAttack: 'আক্রমণ সিমুলেট করুন',
    notifications: 'বিজ্ঞপ্তি',
    liveNotifLog: 'লাইভ বিজ্ঞপ্তি লগ',
    clearAll: 'সব মুছুন',
    noNotif: 'কোন নতুন বিজ্ঞপ্তি নেই',
    teamName: 'উলফপ্যাক স্কোয়াড্রন',
    hackName: 'নেক্সহ্যাক 2.0',
    selectLanguage: 'ভাষা নির্বাচন করুন',
    searchLanguage: 'ভাষা বা দেশ খুঁজুন...',
    indianLanguages: 'ভারতীয় ভাষাসমূহ',
    internationalLanguages: 'আন্তর্জাতিক ভাষাসমূহ',

    // Sidebar
    navDashboard: 'ড্যাশবোর্ড',
    navThreatAlerts: 'হুমকি রাডার',
    navTraffic: 'ট্র্যাফিক অ্যানালিটিক্স',
    navWhatsApp: 'হোয়াটসঅ্যাপ প্রেরণ',
    navSimulator: 'আক্রমণ সিমুলেটর',
    navAuditLogs: 'অডিট লগ',
    navSettings: 'ইঞ্জিন সেটিংস',

    // Metrics Grid
    metricTotalEvents: 'মোট ইনপুট ইভেন্ট',
    metricEventsSub: 'রিয়েল-টাইম স্লাইডিং উইন্ডো টেলিমেট্রি',
    metricAnomalies: 'চিহ্নিত অসঙ্গতি',
    metricAnomaliesSub: 'হিউরিস্টিক + স্পাইক ট্রিগার',
    metricThreatLevel: 'সক্রিয় হুমকির মাত্রা',
    metricThreatLevelSub: 'গতিশীল বেসলাইন মূল্যায়ন',
    metricWhatsApp: 'স্বয়ংক্রিয় হোয়াটসঅ্যাপ বার্তা',
    metricWhatsAppSub: 'সহজ ভাষায় তাত্ক্ষণিক মোবাইল সতর্কতা',
    statusNominal: 'টেলিমেট্রি স্বাভাবিক',
    statusIncidents: 'সংকটপূর্ণ ঘটনা',
    statusStrict: 'কঠোর সুরক্ষা',
    statusDispatched: 'তাত্ক্ষণিক সতর্কতা',

    // Traffic Chart
    chartTitle: 'লাইভ টেলিমেট্রি ইনপুট বনাম অসঙ্গতির স্পাইক',
    chartSub: 'হিউরিস্টিক অসঙ্গতি সহ রিয়েল-টাইম ইভেন্ট ভলিউম',
    chartLegendIngestion: 'ইনজেশন রেট (eps)',
    chartLegendAnomalies: 'অসঙ্গতির সংখ্যা',
    tab15m: '১৫ মিনিট',
    tab1h: '১ ঘন্টা',
    tab24h: '২৪ ঘন্টা',
    filterAll: 'সম্পূর্ণ ট্র্যাফিক',
    filterAnomalies: 'কেবল অসঙ্গতি',
    statPeakRate: 'সর্বোচ্চ ইনপুট রেট',
    statAnomalyRate: 'রিয়েল-টাইম অসঙ্গতির হার',
    statWindow: 'উইন্ডোর স্থায়িত্ব',
    statBaseline: 'বেসলাইন স্থিতি',
    baselineStable: 'স্থিতিশীল (12s)',

    // Threat Feed
    feedTitle: 'রিয়েল-টাইম থ্রেট ইন্টেলিজেন্স ও সহজ বিশ্লেষণ',
    feedSub: 'সহজ ভাষায় তাত্ক্ষণিক অনুবাদ সহ স্লাইডিং-উইন্ডো রাডার',
    feedLiveActive: 'লাইভ স্ট্রিম সক্রিয়',
    filterAllAlerts: 'সমস্ত সতর্কতা',
    filterActive: 'সক্রিয়',
    filterCritical: 'সংকটপূর্ণ',
    filterResolved: 'সমাধান হয়েছে',
    noAlertsFound: 'কোন ঘটনা পাওয়া যায়নি।',
    takeRemediation: 'প্রতিকারমূলক ব্যবস্থা নিন',
    actionCompleted: 'ঘটনা সমাধান ও সুরক্ষিত',
    showTelemetry: 'র টেলিমেট্রি দেখুন',
    hideTelemetry: 'র টেলিমেট্রি লুকান',
    dispatchedToWhatsApp: 'হোয়াটসঅ্যাপে পাঠানো হয়েছে',
    dispatchedTo: 'প্রেরণ প্রাপক:',

    // Hero Card
    heroBadge: 'সহজ ভাষার রাডার',
    heroTitle: 'স্বয়ংক্রিয় হোয়াটসঅ্যাপ হুমকি পাইপলাইন',
    heroSub: 'যখন কোনো অসঙ্গতি ধরা পড়ে, ইঞ্জিন সহজে বোধগম্য বার্তা তৈরি করে হোয়াটসঅ্যাপ এপিআই-এর মাধ্যমে দ্রুত পাঠায়।',
    heroActiveRecipient: 'সক্রিয় প্রাপক:',
    heroBtnTest: 'হোয়াটসঅ্যাপ টেস্ট করুন',
    heroBtnSim: 'সিমুলেটর চালু করুন',

    // General
    languageChangedToast: 'ভাষা পরিবর্তন করা হয়েছে:',
    saveChanges: 'সংরক্ষণ করুন',
    cancel: 'বাতিল',
    close: 'বন্ধ করুন',
  },
  mr: {
    // Nav & Brand
    aiRadar: 'एआय सास रडार',
    radarActive: 'रडार सक्रिय आहे',
    offline: 'ऑफलाइन',
    searchPlaceholder: 'घटना, त्रुटी, आयपी, वापरकर्ते शोधा...',
    simulateAttack: 'हल्ल्याचे अनुकरण करा',
    notifications: 'सूचना',
    liveNotifLog: 'थेट सूचना नोंद',
    clearAll: 'सर्व साफ करा',
    noNotif: 'कोणतीही नवीन सूचना नाही',
    teamName: 'वुल्फपॅक स्क्वॉड्रन',
    hackName: 'नेक्सहॅक 2.0',
    selectLanguage: 'भाषा निवडा',
    searchLanguage: 'भाषा किंवा देश शोधा...',
    indianLanguages: 'भारतीय भाषा',
    internationalLanguages: 'आंतरराष्ट्रीय भाषा',

    // Sidebar
    navDashboard: 'डॅशबोर्ड',
    navThreatAlerts: 'धोका रडार',
    navTraffic: 'वाहतूक विश्लेषण',
    navWhatsApp: 'व्हॉट्सॲप प्रेषण',
    navSimulator: 'हल्ला सिम्युलेटर',
    navAuditLogs: 'ऑडिट लॉग्स',
    navSettings: 'इंजिन सेटिंग्ज',

    // Metrics Grid
    metricTotalEvents: 'एकूण टेलीमेट्री घटना',
    metricEventsSub: 'रिअल-टाइम स्लाइडिंग विंडो टेलीमेट्री',
    metricAnomalies: 'नोंदवलेल्या त्रुटी',
    metricAnomaliesSub: 'ह्युरिस्टिक स्पाइक ट्रिगर्स',
    metricThreatLevel: 'सक्रिय धोका पातळी',
    metricThreatLevelSub: 'डायनॅमिक बेसलाइन मूल्यमापन',
    metricWhatsApp: 'स्वायत्त व्हॉट्सॲप प्रेषण',
    metricWhatsAppSub: 'सोप्या भाषेत त्वरित मोबाइल सूचना',
    statusNominal: 'टेलीमेट्री सामान्य',
    statusIncidents: 'गंभीर घटना',
    statusStrict: 'कडक सुरक्षा',
    statusDispatched: 'त्वरित सूचना',

    // Traffic Chart
    chartTitle: 'थेट टेलीमेट्री इनपुट विरुद्ध त्रुटी स्पाइक्स',
    chartSub: 'रिअल-टाइम स्लाइडिंग विंडो इव्हेंट व्हॉल्यूम',
    chartLegendIngestion: 'इनपुट वेग (eps)',
    chartLegendAnomalies: 'त्रुटींची संख्या',
    tab15m: '१५ मिनिटे',
    tab1h: '१ तास',
    tab24h: '२४ तास',
    filterAll: 'सर्व ट्रॅफिक',
    filterAnomalies: 'केवळ त्रुटी',
    statPeakRate: 'कमाल इनपुट वेग',
    statAnomalyRate: 'रिअल-टाइम त्रुटी दर',
    statWindow: 'विंडो कालावधी',
    statBaseline: 'बेसलाइन स्थिती',
    baselineStable: 'स्थिर (12s)',

    // Threat Feed
    feedTitle: 'रिअल-टाइम थ्रेट इंटेलिजन्स आणि सोपे विश्लेषण',
    feedSub: 'सोप्या मराठी अनुवादासह स्वायत्त स्लाइडिंग-विंडो रडार',
    feedLiveActive: 'थेट प्रवाह सक्रिय',
    filterAllAlerts: 'सर्व सूचना',
    filterActive: 'सक्रिय',
    filterCritical: 'अति-गंभीर',
    filterResolved: 'निवारण झाले',
    noAlertsFound: 'शोध परिणामात कोणतीही घटना आढळली नाही.',
    takeRemediation: 'सुरक्षा कारवाई करा',
    actionCompleted: 'घटना सुरक्षितपणे निवारण झाली',
    showTelemetry: 'रॉ टेलीमेट्री पहा',
    hideTelemetry: 'रॉ टेलीमेट्री लपवा',
    dispatchedToWhatsApp: 'व्हॉट्सॲपवर पाठवले',
    dispatchedTo: 'प्राप्तकर्ता:',

    // Hero Card
    heroBadge: 'सोप्या भाषेतील रडार',
    heroTitle: 'स्वायत्त व्हॉट्सॲप सुरक्षा पाइपलाइन',
    heroSub: 'जेव्हा त्रुटी आढळते, इंजिन तांत्रिक गुंतागुंतीशिवाय सोप्या भाषेतील अलर्ट थेट व्हॉट्सॲपवर पाठवते.',
    heroActiveRecipient: 'सक्रिय प्राप्तकर्ता:',
    heroBtnTest: 'व्हॉट्सॲप चाचणी घ्या',
    heroBtnSim: 'सिम्युलेटर चालवा',

    // General
    languageChangedToast: 'भाषा बदलून केली:',
    saveChanges: 'बदल जतन करा',
    cancel: 'रद्द करा',
    close: 'बंद करा',
  },
  te: {
    // Nav & Brand
    aiRadar: 'AI SaaS రాడార్',
    radarActive: 'రాడార్ సక్రియంగా ఉంది',
    offline: 'ఆఫ్‌లైన్',
    searchPlaceholder: 'సంఘటనలు, అసాధారణతలు, IPలు శోధించండి...',
    simulateAttack: 'దాడిని అనుకరించండి',
    notifications: 'నోటిఫికేషన్లు',
    liveNotifLog: 'లైవ్ నోటిఫికేషన్ లాగ్',
    clearAll: 'అన్నీ తొలగించు',
    noNotif: 'కొత్త నోటిఫికేషన్లు లేవు',
    teamName: 'వోల్ఫ్‌ప్యాక్ స్క్వాడ్రన్',
    hackName: 'నెక్స్‌హ్యాక్ 2.0',
    selectLanguage: 'భాషను ఎంచుకోండి',
    searchLanguage: 'భాష లేదా దేశాన్ని శోధించండి...',
    indianLanguages: 'భారతీయ భాషలు',
    internationalLanguages: 'అంతర్జాతీయ భాషలు',

    // Sidebar
    navDashboard: 'డాష్‌బోర్డ్',
    navThreatAlerts: 'ముప్పు రాడార్',
    navTraffic: 'ట్రాఫిక్ విశ్లేషణ',
    navWhatsApp: 'వాట్సాప్ పంపకం',
    navSimulator: 'దాడి సిమ్యులేటర్',
    navAuditLogs: 'ఆడిట్ లాగ్స్',
    navSettings: 'ఇంజన్ సెట్టింగులు',

    // Metrics Grid
    metricTotalEvents: 'మొత్తం టెలిమెట్రీ ఈవెంట్లు',
    metricEventsSub: 'రియల్-టైమ్ స్లైడింగ్ విండో టెలిమెట్రీ',
    metricAnomalies: 'గుర్తించబడిన అసాధారణతలు',
    metricAnomaliesSub: 'హ్యూరిస్టిక్ + స్పైక్ ట్రిగ్గర్లు',
    metricThreatLevel: 'సక్రియ ముప్పు స్థాయి',
    metricThreatLevelSub: 'డైనమిక్ బేస్‌లైన్ అంచనా',
    metricWhatsApp: 'వాట్సాప్ ద్వారా స్వయంప్రతిపత్తి సందేశాలు',
    metricWhatsAppSub: 'సులభమైన భాషలో తక్షణ మొబైల్ హెచ్చరికలు',
    statusNominal: 'టెలిమెట్రీ సాధారణం',
    statusIncidents: 'తీవ్రమైన సంఘటనలు',
    statusStrict: 'కఠిన రక్షణ',
    statusDispatched: 'తక్షణ హెచ్చరికలు',

    // Traffic Chart
    chartTitle: 'లైవ్ టెలిమెట్రీ ఇన్‌పుట్ vs అసాధారణత స్పైక్‌లు',
    chartSub: 'రియల్-టైమ్ స్లైడింగ్ విండో ఈవెంట్ వాల్యూమ్',
    chartLegendIngestion: 'ఇంజెషన్ రేటు (eps)',
    chartLegendAnomalies: 'అసాధారణతల సంఖ్య',
    tab15m: '15 నిమిషాలు',
    tab1h: '1 గంట',
    tab24h: '24 గంటలు',
    filterAll: 'మొత్తం ట్రాఫిక్',
    filterAnomalies: 'అసాధారణతలు మాత్రమే',
    statPeakRate: 'గరిష్ట ఇన్‌పుట్ రేటు',
    statAnomalyRate: 'రియల్-టైమ్ అసాధారణత రేటు',
    statWindow: 'విండో సమయం',
    statBaseline: 'బేస్‌లైన్ స్థితి',
    baselineStable: 'స్థిరమైనది (12s)',

    // Threat Feed
    feedTitle: 'రియల్-టైమ్ ముప్పు సమాచారం & సరళ భాషా విశ్లేషణ',
    feedSub: 'సరళమైన భాషా అనువాదంతో స్లైడింగ్-విండో టెలిమెట్రీ రాడార్',
    feedLiveActive: 'లైవ్ స్ట్రీమ్ సక్రియంగా ఉంది',
    filterAllAlerts: 'అన్ని హెచ్చరికలు',
    filterActive: 'సక్రియం',
    filterCritical: 'కీలకమైనది',
    filterResolved: 'పరిష్కరించబడింది',
    noAlertsFound: 'మీ శోధనకు సంఘటనలేవీ కనుగొనబడలేదు.',
    takeRemediation: 'రక్షణ చర్య తీసుకోండి',
    actionCompleted: 'సంఘటన పరిష్కరించబడింది & రక్షితం',
    showTelemetry: 'రా టెలిమెట్రీ చూడండి',
    hideTelemetry: 'రా టెలిమెట్రీ దాచండి',
    dispatchedToWhatsApp: 'వాట్సాప్‌కు పంపబడింది',
    dispatchedTo: 'స్వీకర్త:',

    // Hero Card
    heroBadge: 'సులభ భాషా రాడార్',
    heroTitle: 'స్వయంప్రతిపత్తి వాట్సాప్ ముప్పు పైప్‌లైన్',
    heroSub: 'అసాధారణత గుర్తించబడినప్పుడు, ఇంజన్ సులభమైన అలర్ట్‌ను వాట్సాప్ ద్వారా వెంటనే పంపుతుంది.',
    heroActiveRecipient: 'సక్రియ స్వీకర్త:',
    heroBtnTest: 'వాట్సాప్ టెస్ట్ చేయండి',
    heroBtnSim: 'సిమ్యులేటర్ ప్రారంభించండి',

    // General
    languageChangedToast: 'భాష మార్చబడింది:',
    saveChanges: 'మార్పులను భద్రపరచండి',
    cancel: 'రద్దు చేయండి',
    close: 'మూసివేయండి',
  },
  ta: {
    // Nav & Brand
    aiRadar: 'AI SaaS ரேடார்',
    radarActive: 'ரேடார் செயலில் உள்ளது',
    offline: 'ஆஃப்லைன்',
    searchPlaceholder: 'நிகழ்வுகள், முரண்பாடுகள், ஐபிக்கள் தேடுக...',
    simulateAttack: 'தாக்குதலை உருவகப்படுத்துங்கள்',
    notifications: 'அறிவிப்புகள்',
    liveNotifLog: 'நேரலை அறிவிப்பு பதிவு',
    clearAll: 'அனைத்தையும் அழி',
    noNotif: 'புதிய அறிவிப்புகள் இல்லை',
    teamName: 'வுல்ஃபாக் ஸ்குவாட்ரான்',
    hackName: 'நெக்ஸ்ஹேக் 2.0',
    selectLanguage: 'மொழியைத் தேர்ந்தெடுக்கவும்',
    searchLanguage: 'மொழி அல்லது நாட்டைத் தேடுங்கள்...',
    indianLanguages: 'இந்திய மொழிகள்',
    internationalLanguages: 'சர்வதேச மொழிகள்',

    // Sidebar
    navDashboard: 'டாஷ்போர்டு',
    navThreatAlerts: 'அச்சுறுத்தல் ரேடார்',
    navTraffic: 'போக்குவரத்து பகுப்பாய்வு',
    navWhatsApp: 'வாட்ஸ்அப் அனுப்புதல்',
    navSimulator: 'தாக்குதல் சிமுலேட்டர்',
    navAuditLogs: 'தணிக்கை பதிவுகள்',
    navSettings: 'என்ஜின் அமைப்புகள்',

    // Metrics Grid
    metricTotalEvents: 'மொத்த டெலிமெட்ரி நிகழ்வுகள்',
    metricEventsSub: 'நிகழ்நேர ஸ்லைடிங் விண்டோ டெலிமெட்ரி',
    metricAnomalies: 'கண்டறியப்பட்ட முரண்பாடுகள்',
    metricAnomaliesSub: 'ஹியூரிஸ்டிக் ஸ்பைக் தூண்டுதல்கள்',
    metricThreatLevel: 'செயலில் உள்ள அச்சுறுத்தல் நிலை',
    metricThreatLevelSub: 'மாறும் அடிப்படை மதிப்பீடு',
    metricWhatsApp: 'தானியங்கி வாட்ஸ்அப் விழிப்பூட்டல்கள்',
    metricWhatsAppSub: 'எளிய மொழியில் உடனடி மொபைல் எச்சரிக்கை',
    statusNominal: 'டெலிமெட்ரி இயல்பானது',
    statusIncidents: 'முக்கிய நிகழ்வுகள்',
    statusStrict: 'கடுமையான பாதுகாப்பு',
    statusDispatched: 'உடனடி எச்சரிக்கைகள்',

    // Traffic Chart
    chartTitle: 'நேரலை டெலிமெட்ரி உள்ளீடு vs முரண்பாடுகள்',
    chartSub: 'நிகழ்நேர ஸ்லைடிங் விண்டோ நிகழ்வு அளவு',
    chartLegendIngestion: 'உள்ளீட்டு வீதம் (eps)',
    chartLegendAnomalies: 'முரண்பாடுகளின் எண்ணிக்கை',
    tab15m: '15 நிமிடங்கள்',
    tab1h: '1 மணி நேரம்',
    tab24h: '24 மணி நேரம்',
    filterAll: 'அனைத்து போக்குவரத்து',
    filterAnomalies: 'முரண்பாடுகள் மட்டும்',
    statPeakRate: 'அதிகபட்ச உள்ளீட்டு வீதம்',
    statAnomalyRate: 'நிகழ்நேர முரண்பாட்டு விகிதம்',
    statWindow: 'விண்டோ கால அளவு',
    statBaseline: 'அடிப்படை நிலை',
    baselineStable: 'நிலையானது (12s)',

    // Threat Feed
    feedTitle: 'நிகழ்நேர அச்சுறுத்தல் நுண்ணறிவு & எளிய மொழி பகுப்பாய்வு',
    feedSub: 'எளிய மொழி பெயர்ப்புடன் தானியங்கி டெலிமெட்ரி ரேடார்',
    feedLiveActive: 'நேரலை ஸ்ட்ரீம் செயலில் உள்ளது',
    filterAllAlerts: 'அனைத்து எச்சரிக்கைகளும்',
    filterActive: 'செயலில்',
    filterCritical: 'முக்கியமானது',
    filterResolved: 'தீர்க்கப்பட்டது',
    noAlertsFound: 'தேடலுக்கு எந்த நிகழ்வுகளும் கிடைக்கவில்லை.',
    takeRemediation: 'பாதுகாப்பு நடவடிக்கை எடுக்கவும்',
    actionCompleted: 'நிகழ்வு தீர்க்கப்பட்டு பாதுகாக்கப்பட்டது',
    showTelemetry: 'முழு டெலிமெட்ரியைக் காண்க',
    hideTelemetry: 'டெலிமெட்ரியை மறை',
    dispatchedToWhatsApp: 'வாட்ஸ்அப்பில் அனுப்பப்பட்டது',
    dispatchedTo: 'பெறுநர்:',

    // Hero Card
    heroBadge: 'எளிய மொழி ரேடார்',
    heroTitle: 'தானியங்கி வாட்ஸ்அப் அச்சுறுத்தல் குழாய்வழி',
    heroSub: 'முரண்பாடு கண்டறியப்படும்போது, எளிய மொழியில் உடனடியாக வாட்ஸ்அப் வழியாக எச்சரிக்கையை அனுப்புகிறது.',
    heroActiveRecipient: 'செயலில் உள்ள பெறுநர்:',
    heroBtnTest: 'வாட்ஸ்அப் சோதனை செய்க',
    heroBtnSim: 'சிமுலேட்டரைத் தொடங்கு',

    // General
    languageChangedToast: 'மொழி மாற்றப்பட்டது:',
    saveChanges: 'மாற்றங்களைச் சேமி',
    cancel: 'ரத்து செய்',
    close: 'மூடு',
  },
  gu: {
    // Nav & Brand
    aiRadar: 'AI SaaS રડાર',
    radarActive: 'રડાર સક્રિય છે',
    offline: 'ઑફલાઇન',
    searchPlaceholder: 'ઘટનાઓ, વિસંગતતાઓ, IP, વપરાશકર્તાઓ શોધો...',
    simulateAttack: 'હુમલાનું અનુકરણ કરો',
    notifications: 'સૂચનાઓ',
    liveNotifLog: 'લાઇવ સૂચના લૉગ',
    clearAll: 'બધું સાફ કરો',
    noNotif: 'કોઈ નવી સૂચના નથી',
    teamName: 'વુલ્ફપેક સ્ક્વોડ્રન',
    hackName: 'નેક્સહેક 2.0',
    selectLanguage: 'ભાષા પસંદ કરો',
    searchLanguage: 'ભાષા અથવા દેશ શોધો...',
    indianLanguages: 'ભારતીય ભાષાઓ',
    internationalLanguages: 'આંતરરાષ્ટ્રીય ભાષાઓ',

    // Sidebar
    navDashboard: 'ડેશબોર્ડ',
    navThreatAlerts: 'જોખમ રડાર',
    navTraffic: 'ટ્રાફિક વિશ્લેષણ',
    navWhatsApp: 'વોટ્સએપ ડિસ્પેચ',
    navSimulator: 'હુમલો સિમ્યુલેટર',
    navAuditLogs: 'ઓડિટ લૉગ્સ',
    navSettings: 'એન્જિન સેટિંગ્સ',

    // Metrics Grid
    metricTotalEvents: 'કુલ ટેલિમેટ્રી ઇવેન્ટ્સ',
    metricEventsSub: 'રીઅલ-ટાઇમ સ્લાઇડિંગ વિન્ડો ટેલિમેટ્રી',
    metricAnomalies: 'ચિહ્નિત વિસંગતતાઓ',
    metricAnomaliesSub: 'હ્યુરિસ્ટિક સ્પાઇક ટ્રિગર્સ',
    metricThreatLevel: 'સક્રિય જોખમ સ્તર',
    metricThreatLevelSub: 'ડાયનેમિક બેઝલાઇન મૂલ્યાંકન',
    metricWhatsApp: 'સ્વાયત્ત વોટ્સએપ ચેતવણીઓ',
    metricWhatsAppSub: 'સરળ ભાષામાં તાત્કાલિક મોબાઇલ ચેતવણી',
    statusNominal: 'ટેલિમેટ્રી સામાન્ય',
    statusIncidents: 'ગંભીર ઘટનાઓ',
    statusStrict: 'સખત સુરક્ષા',
    statusDispatched: 'ત્વરિત ચેતવણી',

    // Traffic Chart
    chartTitle: 'લાઇવ ટેલિમેટ્રી ઇનપુટ વિરુદ્ધ વિસંગતતાઓ',
    chartSub: 'રીઅલ-ટાઇમ સ્લાઇડિંગ વિન્ડો ઇવેન્ટ વોલ્યુમ',
    chartLegendIngestion: 'ઇન્જેશન દર (eps)',
    chartLegendAnomalies: 'વિસંગતતાઓની સંખ્યા',
    tab15m: '15 મિનિટ',
    tab1h: '1 કલાક',
    tab24h: '24 કલાક',
    filterAll: 'સમગ્ર ટ્રાફિક',
    filterAnomalies: 'માત્ર વિસંગતતાઓ',
    statPeakRate: 'મહત્તમ ઇનપુટ દર',
    statAnomalyRate: 'રીઅલ-ટાઇમ વિસંગતતા દર',
    statWindow: 'વિન્ડો સમયગાળો',
    statBaseline: 'બેઝલાઇન સ્થિતિ',
    baselineStable: 'સ્થિર (12s)',

    // Threat Feed
    feedTitle: 'રીઅલ-ટાઇમ થ્રેટ ઇન્ટેલિજન્સ અને સરળ વિશ્લેષણ',
    feedSub: 'સરળ ભાષા અનુવાદ સાથે સ્લાઇડિંગ-વિન્ડો રડાર',
    feedLiveActive: 'લાઇવ પ્રવાહ સક્રિય છે',
    filterAllAlerts: 'બધી ચેતવણીઓ',
    filterActive: 'સક્રિય',
    filterCritical: 'અતિ-ગંભીર',
    filterResolved: 'ઉકેલાયેલ',
    noAlertsFound: 'કોઈ ઘટના મળી નથી.',
    takeRemediation: 'સુરક્ષા પગલાં લો',
    actionCompleted: 'ઘટના ઉકેલાઈ ગઈ છે અને સુરક્ષિત છે',
    showTelemetry: 'રો ટેલિમેટ્રી જુઓ',
    hideTelemetry: 'રો ટેલિમેટ્રી છુપાવો',
    dispatchedToWhatsApp: 'વોટ્સએપ પર મોકલવામાં આવ્યું',
    dispatchedTo: 'પ્રાપ્તકર્તા:',

    // Hero Card
    heroBadge: 'સરળ ભાષા રડાર',
    heroTitle: 'સ્વાયત્ત વોટ્સએપ જોખમ પાઇપલાઇન',
    heroSub: 'જ્યારે કોઈ વિસંગતતા જણાય ત્યારે એન્જિન સરળ એલર્ટ વોટ્સએપ પર મોકલે છે.',
    heroActiveRecipient: 'સક્રિય પ્રાપ્તકર્તા:',
    heroBtnTest: 'વોટ્સએપ ટેસ્ટ કરો',
    heroBtnSim: 'સિમ્યુલેટર શરૂ કરો',

    // General
    languageChangedToast: 'ભાષા બદલીને કરવામાં આવી:',
    saveChanges: 'ફેરફારો સાચવો',
    cancel: 'રદ કરો',
    close: 'બંધ કરો',
  },
  kn: {
    // Nav & Brand
    aiRadar: 'AI SaaS ರೇಡಾರ್',
    radarActive: 'ರೇಡಾರ್ ಸಕ್ರಿಯವಾಗಿದೆ',
    offline: 'ಆಫ್‌ಲೈನ್',
    searchPlaceholder: 'ಘಟನೆಗಳು, ಅಸಂಗತತೆಗಳು, IP ಗಳು ಹುಡುಕಿ...',
    simulateAttack: 'ದಾಳಿಯನ್ನು ಅನುಕರಿಸಿ',
    notifications: 'ಸೂಚನೆಗಳು',
    liveNotifLog: 'ಲೈವ್ ಸೂಚನಾ ಲಾಗ್',
    clearAll: 'ಎಲ್ಲವನ್ನೂ ತೆರವುಗೊಳಿಸಿ',
    noNotif: 'ಯಾವುದೇ ಹೊಸ ಸೂಚನೆಗಳಿಲ್ಲ',
    teamName: 'ವುಲ್ಫ್‌ಪ್ಯಾಕ್ ಸ್ಕ್ವಾಡ್ರನ್',
    hackName: 'ನೆಕ್ಸ್‌ಹ್ಯಾಕ್ 2.0',
    selectLanguage: 'ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    searchLanguage: 'ಭಾಷೆ ಅಥವಾ ದೇಶವನ್ನು ಹುಡುಕಿ...',
    indianLanguages: 'ಭಾರತೀಯ ಭಾಷೆಗಳು',
    internationalLanguages: 'ಅಂತರರಾಷ್ಟ್ರೀಯ ಭಾಷೆಗಳು',

    // Sidebar
    navDashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    navThreatAlerts: 'ಬೆದರಿಕೆ ರೇಡಾರ್',
    navTraffic: 'ಟ್ರಾಫಿಕ್ ವಿಶ್ಲೇಷಣೆ',
    navWhatsApp: 'ವಾಟ್ಸಾಪ್ ರವಾನೆ',
    navSimulator: 'ದಾಳಿ ಸಿಮ್ಯುಲೇಟರ್',
    navAuditLogs: 'ಆಡಿಟ್ ಲಾಗ್‌ಗಳು',
    navSettings: 'ಎಂಜಿನ್ ಸೆಟ್ಟಿಂಗ್‌ಗಳು',

    // Metrics Grid
    metricTotalEvents: 'ಒಟ್ಟು ಟೆಲಿಮೆಟ್ರಿ ಈವೆಂಟ್‌ಗಳು',
    metricEventsSub: 'ನೈಜ-ಸಮಯದ ಸ್ಲೈಡಿಂಗ್ ವಿಂಡೋ ಟೆಲಿಮೆಟ್ರಿ',
    metricAnomalies: 'ಗುರುತಿಸಲಾದ ಅಸಂಗತತೆಗಳು',
    metricAnomaliesSub: 'ಹ್ಯೂರಿಸ್ಟಿಕ್ ಸ್ಪೈಕ್ ಪ್ರಚೋದಕಗಳು',
    metricThreatLevel: 'ಸಕ್ರಿಯ ಬೆದರಿಕೆ ಮಟ್ಟ',
    metricThreatLevelSub: 'ಡೈನಾಮಿಕ್ ಬೇಸ್‌ಲೈನ್ ಮೌಲ್ಯಮಾಪನ',
    metricWhatsApp: 'ಸ್ವಾಯತ್ತ ವಾಟ್ಸಾಪ್ ಎಚ್ಚರಿಕೆಗಳು',
    metricWhatsAppSub: 'ಸರಳ ಭಾಷೆಯಲ್ಲಿ ತ್ವರಿತ ಮೊಬೈಲ್ ಎಚ್ಚರಿಕೆ',
    statusNominal: 'ಟೆಲಿಮೆಟ್ರಿ ಸಾಮಾನ್ಯ',
    statusIncidents: 'ಗಂಭೀರ ಘಟನೆಗಳು',
    statusStrict: 'ಕಟ್ಟುನಿಟ್ಟಿನ ರಕ್ಷಣೆ',
    statusDispatched: 'ತ್ವರಿತ ಎಚ್ಚರಿಕೆಗಳು',

    // Traffic Chart
    chartTitle: 'ಲೈವ್ ಟೆಲಿಮೆಟ್ರಿ ಇನ್‌ಪುಟ್ vs ಅಸಂಗತತೆಗಳು',
    chartSub: 'ನೈಜ-ಸಮಯದ ಸ್ಲೈಡಿಂಗ್ ವಿಂಡೋ ಈವೆಂಟ್ ವಾಲ್ಯೂಮ್',
    chartLegendIngestion: 'ಇಂಜೆಷನ್ ದರ (eps)',
    chartLegendAnomalies: 'ಅಸಂಗತತೆಗಳ ಸಂಖ್ಯೆ',
    tab15m: '15 ನಿಮಿಷಗಳು',
    tab1h: '1 ಗಂಟೆ',
    tab24h: '24 ಗಂಟೆಗಳು',
    filterAll: 'ಸಂಪೂರ್ಣ ಸಂಚಾರ',
    filterAnomalies: 'ಕೇವಲ ಅಸಂಗತತೆಗಳು',
    statPeakRate: 'ಗರಿಷ್ಠ ಇನ್‌ಪುಟ್ ದರ',
    statAnomalyRate: 'ನೈಜ-ಸಮಯದ ಅಸಂಗತತೆ ದರ',
    statWindow: 'ವಿಂಡೋ ಅವಧಿ',
    statBaseline: 'ಬೇಸ್‌ಲೈನ್ ಸ್ಥಿತಿ',
    baselineStable: 'ಸ್ಥಿರವಾಗಿದೆ (12s)',

    // Threat Feed
    feedTitle: 'ನೈಜ-ಸಮಯದ ಬೆದರಿಕೆ ಗುಪ್ತಚರ ಮತ್ತು ಸರಳ ವಿಶ್ಲೇಷಣೆ',
    feedSub: 'ಸರಳ ಭಾಷಾ ಅನುವಾದದೊಂದಿಗೆ ಸ್ಲೈಡಿಂಗ್-ವಿಂಡೋ ರೇಡಾರ್',
    feedLiveActive: 'ಲೈವ್ ಸ್ಟ್ರೀಮ್ ಸಕ್ರಿಯವಾಗಿದೆ',
    filterAllAlerts: 'ಎಲ್ಲಾ ಎಚ್ಚರಿಕೆಗಳು',
    filterActive: 'ಸಕ್ರಿಯ',
    filterCritical: 'ಅತಿ-ಗಂಭೀರ',
    filterResolved: 'ಪರಿಹರಿಸಲಾಗಿದೆ',
    noAlertsFound: 'ಯಾವುದೇ ಘಟನೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ.',
    takeRemediation: 'ರಕ್ಷಣಾ ಕ್ರಮ ಕೈಗೊಳ್ಳಿ',
    actionCompleted: 'ಘಟನೆ ಪರಿಹರಿಸಲಾಗಿದೆ ಮತ್ತು ಸುರಕ್ಷಿತವಾಗಿದೆ',
    showTelemetry: 'ರಾ ಟೆಲಿಮೆಟ್ರಿ ವೀಕ್ಷಿಸಿ',
    hideTelemetry: 'ರಾ ಟೆಲಿಮೆಟ್ರಿ ಮರೆಮಾಡಿ',
    dispatchedToWhatsApp: 'ವಾಟ್ಸಾಪ್‌ಗೆ ಕಳುಹಿಸಲಾಗಿದೆ',
    dispatchedTo: 'ಸ್ವೀಕರಿಸುವವರು:',

    // Hero Card
    heroBadge: 'ಸರಳ ಭಾಷೆಯ ರೇಡಾರ್',
    heroTitle: 'ಸ್ವಾಯತ್ತ ವಾಟ್ಸಾಪ್ ಬೆದರಿಕೆ ಪೈಪ್‌ಲೈನ್',
    heroSub: 'ಅಸಂಗತತೆ ಪತ್ತೆಯಾದಾಗ, ಎಂಜಿನ್ ಸುಲಭವಾದ ಎಚ್ಚರಿಕೆಯನ್ನು ವಾಟ್ಸಾಪ್ ಮೂಲಕ ರವಾನಿಸುತ್ತದೆ.',
    heroActiveRecipient: 'ಸಕ್ರಿಯ ಸ್ವೀಕರಿಸುವವರು:',
    heroBtnTest: 'ವಾಟ್ಸಾಪ್ ಪರೀಕ್ಷಿಸಿ',
    heroBtnSim: 'ಸಿಮ್ಯುಲೇಟರ್ ಪ್ರಾರಂಭಿಸಿ',

    // General
    languageChangedToast: 'ಭಾಷೆಯನ್ನು ಬದಲಾಯಿಸಲಾಗಿದೆ:',
    saveChanges: 'ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ',
    cancel: 'ರದ್ದುಮಾಡಿ',
    close: 'ಮುಚ್ಚಿ',
  },
  ml: {
    // Nav & Brand
    aiRadar: 'AI SaaS റഡാർ',
    radarActive: 'റഡാർ സജീവമാണ്',
    offline: 'ഓഫ്‌ലൈൻ',
    searchPlaceholder: 'സംഭവങ്ങൾ, അപാകതകൾ, IP തിരയുക...',
    simulateAttack: 'ആക്രമണം സിമുലേറ്റ് ചെയ്യുക',
    notifications: 'അറിയിപ്പുകൾ',
    liveNotifLog: 'തത്സമയ അറിയിപ്പ് ലോഗ്',
    clearAll: 'എല്ലാം മായ്‌ക്കുക',
    noNotif: 'പുതിയ അറിയിപ്പുകളൊന്നുമില്ല',
    teamName: 'വുൾഫ്പാക്ക് സ്ക്വാഡ്രൺ',
    hackName: 'നെക്സ്ഹാക്ക് 2.0',
    selectLanguage: 'ഭാഷ തിരഞ്ഞെടുക്കുക',
    searchLanguage: 'ഭാഷ അല്ലെങ്കിൽ രാജ്യം തിരയുക...',
    indianLanguages: 'ഇന്ത്യൻ ഭാഷകൾ',
    internationalLanguages: 'അന്താരാഷ്ട്ര ഭാഷകൾ',

    // Sidebar
    navDashboard: 'ഡാഷ്‌ബോർഡ്',
    navThreatAlerts: 'ഭീഷണി റഡാർ',
    navTraffic: 'ട്രാഫിക് അനലിറ്റിക്സ്',
    navWhatsApp: 'വാട്ട്‌സ്ആപ്പ് ഡിസ്പാച്ച്',
    navSimulator: 'ആക്രമണ സിമുലേറ്റർ',
    navAuditLogs: 'ഓഡിറ്റ് ലോഗുകൾ',
    navSettings: 'എഞ്ചിൻ ക്രമീകരണങ്ങൾ',

    // Metrics Grid
    metricTotalEvents: 'ആകെ ടെലിമെട്രി ഇവന്റുകൾ',
    metricEventsSub: 'തത്സമയ സ്ലൈഡിംഗ് വിൻഡോ ടെലിമെട്രി',
    metricAnomalies: 'കണ്ടെത്തിയ അപാകതകൾ',
    metricAnomaliesSub: 'ഹ്യൂറിസ്റ്റിക് സ്പൈക്ക് ട്രിഗറുകൾ',
    metricThreatLevel: 'സജീവ ഭീഷണി നില',
    metricThreatLevelSub: 'ഡൈനാമിക് ബേസ്‌ലൈൻ വിലയിരുത്തൽ',
    metricWhatsApp: 'വാട്ട്‌സ്ആപ്പ് വഴിയുള്ള അറിയിപ്പുകൾ',
    metricWhatsAppSub: 'ലളിതമായ ഭാഷയിൽ തൽക്ഷണ മൊബൈൽ മുന്നറിയിപ്പ്',
    statusNominal: 'ടെലിമെട്രി സാധാരണ നിലയിൽ',
    statusIncidents: 'ഗുരുതരമായ സംഭവങ്ങൾ',
    statusStrict: 'കർശനമായ സുരക്ഷ',
    statusDispatched: 'തൽക്ഷണ മുന്നറിയിപ്പുകൾ',

    // Traffic Chart
    chartTitle: 'തത്സമയ ടെലിമെട്രി ഇൻപുട്ടും അപാകതകളും',
    chartSub: 'തത്സമയ സ്ലൈഡിംഗ് വിൻഡോ ഇവന്റ് വോളിയം',
    chartLegendIngestion: 'ഇൻപുട്ട് നിരക്ക് (eps)',
    chartLegendAnomalies: 'അപാകതകളുടെ എണ്ണം',
    tab15m: '15 മിനിറ്റ്',
    tab1h: '1 മണിക്കൂർ',
    tab24h: '24 മണിക്കൂർ',
    filterAll: 'മുഴുവൻ ട്രാഫിക്',
    filterAnomalies: 'അപാകതകൾ മാത്രം',
    statPeakRate: 'ഉയർന്ന ഇൻപുട്ട് നിരക്ക്',
    statAnomalyRate: 'തത്സമയ അപാകത നിരക്ക്',
    statWindow: 'വിൻഡോ ദൈർഘ്യം',
    statBaseline: 'ബേസ്‌ലൈൻ നില',
    baselineStable: 'സ്ഥിരതയുള്ളത് (12s)',

    // Threat Feed
    feedTitle: 'തത്സമയ ഭീഷണി വിവരങ്ങളും ലളിതമായ വിശകലനവും',
    feedSub: 'ലളിതമായ ഭാഷാ വിവർത്തനത്തോടുകൂടിയ റഡാർ',
    feedLiveActive: 'തത്സമയ സ്ട്രീം സജീവമാണ്',
    filterAllAlerts: 'എല്ലാ മുന്നറിയിപ്പുകളും',
    filterActive: 'സജീവം',
    filterCritical: 'ഗുരുതരം',
    filterResolved: 'പരിഹരിച്ചു',
    noAlertsFound: 'സംഭവങ്ങളൊന്നും കണ്ടെത്തിയില്ല.',
    takeRemediation: 'സുരക്ഷാ നടപടിയെടുക്കുക',
    actionCompleted: 'സംഭവം പരിഹരിച്ച് സുരക്ഷിതമാക്കി',
    showTelemetry: 'റോ ടെലിമെട്രി കാണുക',
    hideTelemetry: 'റോ ടെലിമെട്രി മറയ്ക്കുക',
    dispatchedToWhatsApp: 'വാട്ട്‌സ്ആപ്പിലേക്ക് അയച്ചു',
    dispatchedTo: 'സ്വീകർത്താവ്:',

    // Hero Card
    heroBadge: 'ലളിത ഭാഷാ റഡാർ',
    heroTitle: 'വാട്ട്‌സ്ആപ്പ് ഭീഷണി പൈപ്പ്‌ലൈൻ',
    heroSub: 'അപാകത കണ്ടെത്തുമ്പോൾ എഞ്ചിൻ ലളിതമായ മുന്നറിയിപ്പ് വാട്ട്‌സ്ആപ്പ് വഴി അയയ്ക്കുന്നു.',
    heroActiveRecipient: 'സജീവ സ്വീകർത്താവ്:',
    heroBtnTest: 'വാട്ട്‌സ്ആപ്പ് പരീക്ഷിക്കുക',
    heroBtnSim: 'സിമുലേറ്റർ ആരംഭിക്കുക',

    // General
    languageChangedToast: 'ഭാഷ മാറ്റി:',
    saveChanges: 'മാറ്റങ്ങൾ സംരക്ഷിക്കുക',
    cancel: 'റദ്ദാക്കുക',
    close: 'അടയ്ക്കുക',
  },
  pa: {
    // Nav & Brand
    aiRadar: 'AI SaaS ਰਾਡਾਰ',
    radarActive: 'ਰਾਡਾਰ ਕਿਰਿਆਸ਼ੀਲ ਹੈ',
    offline: 'ਔਫਲਾਈਨ',
    searchPlaceholder: 'ਘਟਨਾਵਾਂ, ਖ਼ਤਰੇ, IP, ਵਰਤੋਂਕਾਰ ਖੋਜੋ...',
    simulateAttack: 'ਹਮਲੇ ਦਾ ਸਿਮੂਲੇਸ਼ਨ ਕਰੋ',
    notifications: 'ਸੂਚਨਾਵਾਂ',
    liveNotifLog: 'ਲਾਈਵ ਸੂਚਨਾ ਲੌਗ',
    clearAll: 'ਸਭ ਸਾਫ਼ ਕਰੋ',
    noNotif: 'ਕੋਈ ਨਵੀਂ ਸੂਚਨਾ ਨਹੀਂ',
    teamName: 'ਵੁਲਫਪੈਕ ਸਕੁਐਡਰਨ',
    hackName: 'ਨੈਕਸਹੈਕ 2.0',
    selectLanguage: 'ਭਾਸ਼ਾ ਚੁਣੋ',
    searchLanguage: 'ਭਾਸ਼ਾ ਜਾਂ ਦੇਸ਼ ਖੋਜੋ...',
    indianLanguages: 'ਭਾਰਤੀ ਭਾਸ਼ਾਵਾਂ',
    internationalLanguages: 'ਅੰਤਰਰਾਸ਼ਟਰੀ ਭਾਸ਼ਾਵਾਂ',

    // Sidebar
    navDashboard: 'ਡੈਸ਼ਬੋਰਡ',
    navThreatAlerts: 'ਖ਼ਤਰਾ ਰਾਡਾਰ',
    navTraffic: 'ਟ੍ਰੈਫਿਕ ਵਿਸ਼ਲੇਸ਼ਣ',
    navWhatsApp: 'ਵਟਸਐਪ ਭੇਜੋ',
    navSimulator: 'ਹਮਲਾ ਸਿਮੂਲੇਟਰ',
    navAuditLogs: 'ਆਡਿਟ ਲੌਗ',
    navSettings: 'ਇੰਜਨ ਸੈਟਿੰਗਾਂ',

    // Metrics Grid
    metricTotalEvents: 'ਕੁੱਲ ਟੈਲੀਮੈਟਰੀ ਘਟਨਾਵਾਂ',
    metricEventsSub: 'ਰੀਅਲ-ਟਾਈਮ ਸਲਾਈਡਿੰਗ ਵਿੰਡੋ ਟੈਲੀਮੈਟਰੀ',
    metricAnomalies: 'ਪਛਾਣੇ ਗਏ ਖ਼ਤਰੇ',
    metricAnomaliesSub: 'ਹਿਊਰਿਸਟਿਕ ਸਪਾਈਕ ਟਰਿੱਗਰ',
    metricThreatLevel: 'ਕਿਰਿਆਸ਼ੀਲ ਖ਼ਤਰਾ ਪੱਧਰ',
    metricThreatLevelSub: 'ਡਾਇਨਾਮਿਕ ਬੇਸਲਾਈਨ ਮੁਲਾਂਕਣ',
    metricWhatsApp: 'ਵਟਸਐਪ ਰਾਹੀਂ ਚੇਤਾਵਨੀਆਂ',
    metricWhatsAppSub: 'ਸੌਖੀ ਭਾਸ਼ਾ ਵਿੱਚ ਤੁਰੰਤ ਮੋਬਾਈਲ ਅਲਰਟ',
    statusNominal: 'ਟੈਲੀਮੈਟਰੀ ਆਮ ਹੈ',
    statusIncidents: 'ਗੰਭੀਰ ਘਟਨਾਵਾਂ',
    statusStrict: 'ਸਖ਼ਤ ਸੁਰੱਖਿਆ',
    statusDispatched: 'ਤੁਰੰਤ ਅਲਰਟ',

    // Traffic Chart
    chartTitle: 'ਲਾਈਵ ਟੈਲੀਮੈਟਰੀ ਇਨਪੁਟ ਬਨਾਮ ਖ਼ਤਰੇ',
    chartSub: 'ਰੀਅਲ-ਟਾਈਮ ਸਲਾਈਡਿੰਗ ਵਿੰਡੋ ਇਵੈਂਟ ਵਾਲੀਅਮ',
    chartLegendIngestion: 'ਇਨਪੁਟ ਦਰ (eps)',
    chartLegendAnomalies: 'ਖ਼ਤਰਿਆਂ ਦੀ ਗਿਣਤੀ',
    tab15m: '15 ਮਿੰਟ',
    tab1h: '1 ਘੰਟਾ',
    tab24h: '24 ਘੰਟੇ',
    filterAll: 'ਸਾਰਾ ਟ੍ਰੈਫਿਕ',
    filterAnomalies: 'ਸਿਰਫ਼ ਖ਼ਤਰੇ',
    statPeakRate: 'ਵੱਧ ਤੋਂ ਵੱਧ ਇਨਪੁਟ ਦਰ',
    statAnomalyRate: 'ਰੀਅਲ-ਟਾਈਮ ਖ਼ਤਰਾ ਦਰ',
    statWindow: 'ਵਿੰਡੋ ਸਮਾਂ',
    statBaseline: 'ਬੇਸਲਾਈਨ ਸਥਿਤੀ',
    baselineStable: 'ਸਥਿਰ (12s)',

    // Threat Feed
    feedTitle: 'ਰੀਅਲ-ਟਾਈਮ ਥ੍ਰੈਟ ਇੰਟੈਲੀਜੈਂਸ ਅਤੇ ਸਰਲ ਵਿਸ਼ਲੇਸ਼ਣ',
    feedSub: 'ਸਰਲ ਭਾਸ਼ਾ ਅਨੁਵਾਦ ਨਾਲ ਟੈਲੀਮੈਟਰੀ ਰਾਡਾਰ',
    feedLiveActive: 'ਲਾਈਵ ਸਟ੍ਰੀਮ ਕਿਰਿਆਸ਼ੀਲ ਹੈ',
    filterAllAlerts: 'ਸਾਰੇ ਅਲਰਟ',
    filterActive: 'ਕਿਰਿਆਸ਼ੀਲ',
    filterCritical: 'ਅਤਿ-ਗੰਭੀਰ',
    filterResolved: 'ਹੱਲ ਕੀਤਾ ਗਿਆ',
    noAlertsFound: 'ਕੋਈ ਘਟਨਾ ਨਹੀਂ ਮਿਲੀ।',
    takeRemediation: 'ਸੁਰੱਖਿਆ ਕਾਰਵਾਈ ਕਰੋ',
    actionCompleted: 'ਘਟਨਾ ਹੱਲ ਹੋਈ ਅਤੇ ਸੁਰੱਖਿਅਤ ਹੈ',
    showTelemetry: 'ਰਾ ਟੈਲੀਮੈਟਰੀ ਵੇਖੋ',
    hideTelemetry: 'ਰਾ ਟੈਲੀਮੈਟਰੀ ਲੁਕਾਓ',
    dispatchedToWhatsApp: 'ਵਟਸਐਪ ਤੇ ਭੇਜਿਆ ਗਿਆ',
    dispatchedTo: 'ਪ੍ਰਾਪਤਕਰਤਾ:',

    // Hero Card
    heroBadge: 'ਸੌਖੀ ਭਾਸ਼ਾ ਰਾਡਾਰ',
    heroTitle: 'ਵਟਸਐਪ ਖ਼ਤਰਾ ਪਾਈਪਲਾਈਨ',
    heroSub: 'ਖ਼ਤਰਾ ਮਿਲਣ ਤੇ ਇੰਜਨ ਸੌਖੀ ਭਾਸ਼ਾ ਵਿੱਚ ਵਟਸਐਪ ਤੇ ਅਲਰਟ ਭੇਜਦਾ ਹੈ।',
    heroActiveRecipient: 'ਕਿਰਿਆਸ਼ੀਲ ਪ੍ਰਾਪਤਕਰਤਾ:',
    heroBtnTest: 'ਵਟਸਐਪ ਟੈਸਟ ਕਰੋ',
    heroBtnSim: 'ਸਿਮੂਲੇਟਰ ਚਲਾਓ',

    // General
    languageChangedToast: 'ਭਾਸ਼ਾ ਬਦਲ ਦਿੱਤੀ ਗਈ:',
    saveChanges: 'ਤਬਦੀਲੀਆਂ ਸੰਭਾਲੋ',
    cancel: 'ਰੱਦ ਕਰੋ',
    close: 'ਬੰਦ ਕਰੋ',
  },
  or: {
    // Nav & Brand
    aiRadar: 'AI SaaS ରାଡାର୍',
    radarActive: 'ରାଡାର୍ ସକ୍ରିୟ ଅଛି',
    offline: 'ଅଫଲାଇନ୍',
    searchPlaceholder: 'ଘଟଣା, ଅସଙ୍ଗତି, IP ଖୋଜନ୍ତୁ...',
    simulateAttack: 'ଆକ୍ରମଣ ଅନୁକରଣ କରନ୍ତୁ',
    notifications: 'ବିଜ୍ଞପ୍ତି',
    liveNotifLog: 'ଲାଇଭ୍ ବିଜ୍ଞପ୍ତି ଲଗ୍',
    clearAll: 'ସବୁ ସଫା କରନ୍ତୁ',
    noNotif: 'କୌଣସି ନୂଆ ବିଜ୍ଞପ୍ତି ନାହିଁ',
    teamName: 'ୱୁଲଫ୍‌ପ୍ୟାକ୍ ସ୍କ୍ୱାଡ୍ରନ୍',
    hackName: 'ନେକ୍ସହ୍ୟାକ୍ 2.0',
    selectLanguage: 'ଭାଷା ବାଛନ୍ତୁ',
    searchLanguage: 'ଭାଷା ବା ଦେଶ ଖୋଜନ୍ତୁ...',
    indianLanguages: 'ଭାରତୀୟ ଭାଷାସମୂହ',
    internationalLanguages: 'ଆନ୍ତର୍ଜାତୀୟ ଭାଷା',

    // Sidebar
    navDashboard: 'ଡ୍ୟାସବୋର୍ଡ',
    navThreatAlerts: 'ବିପଦ ରାଡାର୍',
    navTraffic: 'ଟ୍ରାଫିକ୍ ବିଶ୍ଳେଷଣ',
    navWhatsApp: 'ହ୍ୱାଟ୍ସଆପ୍ ପ୍ରେରଣ',
    navSimulator: 'ଆକ୍ରମଣ ସିମ୍ୟୁଲେଟର',
    navAuditLogs: 'ଅଡିଟ୍ ଲଗ୍',
    navSettings: 'ଇଞ୍ଜିନ୍ ସେଟିଙ୍ଗ୍ସ',

    // Metrics Grid
    metricTotalEvents: 'ସମୁଦାୟ ଟେଲିମେଟ୍ରି ଘଟଣା',
    metricEventsSub: 'ରିଅଲ-ଟାଇମ୍ ସ୍ଲାଇଡିଂ ୱିଣ୍ଡୋ ଟେଲିମେଟ୍ରି',
    metricAnomalies: 'ଚିହ୍ନଟ ଅସଙ୍ଗତି',
    metricAnomaliesSub: 'ହିଉରିଷ୍ଟିକ୍ ସ୍ପାଇକ୍ ଟ୍ରିଗର୍',
    metricThreatLevel: 'ସକ୍ରିୟ ବିପଦ ସ୍ତର',
    metricThreatLevelSub: 'ଗତିଶୀଳ ବେସଲାଇନ୍ ମୂଲ୍ୟାଙ୍କନ',
    metricWhatsApp: 'ହ୍ୱାଟ୍ସଆପ୍ ବାର୍ତ୍ତା',
    metricWhatsAppSub: 'ସହଜ ଭାଷାରେ ତତକ୍ଷଣାତ୍ ମୋବାଇଲ୍ ସତର୍କତା',
    statusNominal: 'ଟେଲିମେଟ୍ରି ସାଧାରଣ',
    statusIncidents: 'ଗୁରୁତର ଘଟଣା',
    statusStrict: 'କଡ଼ା ସୁରକ୍ଷା',
    statusDispatched: 'ତୁରନ୍ତ ସତର୍କତା',

    // Traffic Chart
    chartTitle: 'ଲାଇଭ୍ ଟେଲିମେଟ୍ରି ଇନପୁଟ୍ ବନାମ ଅସଙ୍ଗତି',
    chartSub: 'ରିଅଲ-ଟାଇମ୍ ସ୍ଲାଇଡିଂ ୱିଣ୍ଡୋ ଇଭେଣ୍ଟ ଭଲ୍ୟୁମ୍',
    chartLegendIngestion: 'ଇନପୁଟ୍ ହାର (eps)',
    chartLegendAnomalies: 'ଅସଙ୍ଗତି ସଂଖ୍ୟା',
    tab15m: '15 ମିନିଟ୍',
    tab1h: '1 ଘଣ୍ଟା',
    tab24h: '24 ଘଣ୍ଟା',
    filterAll: 'ସମଗ୍ର ଟ୍ରାଫିକ୍',
    filterAnomalies: 'କେବଳ ଅସଙ୍ଗତି',
    statPeakRate: 'ସର୍ବାଧିକ ଇନପୁଟ୍ ହାର',
    statAnomalyRate: 'ରିଅଲ-ଟାଇମ୍ ଅସଙ୍ଗତି ହାର',
    statWindow: 'ୱିଣ୍ଡୋ ଅବଧି',
    statBaseline: 'ବେସଲାଇନ୍ ସ୍ଥିତି',
    baselineStable: 'ସ୍ଥିର (12s)',

    // Threat Feed
    feedTitle: 'ରିଅଲ-ଟାଇମ୍ ଥ୍ରେଟ୍ ଇଣ୍ଟେଲିଜେନ୍ସ ଓ ସରଳ ବିଶ୍ଳେଷଣ',
    feedSub: 'ସରଳ ଭାଷା ଅନୁବାଦ ସହିତ ଟେଲିମେଟ୍ରି ରାଡାର୍',
    feedLiveActive: 'ଲାଇଭ୍ ଷ୍ଟ୍ରିମ୍ ସକ୍ରିୟ ଅଛି',
    filterAllAlerts: 'ସମସ୍ତ ସତର୍କତା',
    filterActive: 'ସକ୍ରିୟ',
    filterCritical: 'ଗୁରୁତର',
    filterResolved: 'ସମାଧାନ ହୋଇଛି',
    noAlertsFound: 'କୌଣସି ଘଟଣା ମିଳିଲା ନାହିଁ।',
    takeRemediation: 'ସୁରକ୍ଷା କାର୍ଯ୍ୟାନୁଷ୍ଠାନ ଗ୍ରହଣ କରନ୍ତୁ',
    actionCompleted: 'ଘଟଣା ସମାଧାନ ହୋଇଛି ଏବଂ ସୁରକ୍ଷିତ',
    showTelemetry: 'ର ଟେଲିମେଟ୍ରି ଦେଖନ୍ତୁ',
    hideTelemetry: 'ଟେଲିମେଟ୍ରି ଲୁଚାନ୍ତୁ',
    dispatchedToWhatsApp: 'ହ୍ୱାଟ୍ସଆପ୍‌ରେ ପଠାଗଲା',
    dispatchedTo: 'ପ୍ରାପ୍ତକର୍ତ୍ତା:',

    // Hero Card
    heroBadge: 'ସରଳ ଭାଷା ରାଡାର୍',
    heroTitle: 'ହ୍ୱାଟ୍ସଆପ୍ ବିପଦ ପାଇପଲାଇନ୍',
    heroSub: 'ଅସଙ୍ଗତି ମିଳିଲେ ଇଞ୍ଜିନ୍ ସରଳ ବାର୍ତ୍ତା ହ୍ୱାଟ୍ସଆପ୍ ମାଧ୍ୟମରେ ପଠାଏ।',
    heroActiveRecipient: 'ସକ୍ରିୟ ପ୍ରାପ୍ତକର୍ତ୍ତା:',
    heroBtnTest: 'ହ୍ୱାଟ୍ସଆପ୍ ପରୀକ୍ଷା କରନ୍ତୁ',
    heroBtnSim: 'ସିମ୍ୟୁଲେଟର ଆରମ୍ଭ କରନ୍ତୁ',

    // General
    languageChangedToast: 'ଭାଷା ପରିବର୍ତ୍ତନ ହୋଇଛି:',
    saveChanges: 'ସଂରକ୍ଷଣ କରନ୍ତୁ',
    cancel: 'ବାତିଲ୍',
    close: 'ବନ୍ଦ କରନ୍ତୁ',
  },
  as: {
    // Nav & Brand
    aiRadar: 'AI SaaS ৰাডাৰ',
    radarActive: 'ৰাডাৰ সক্ৰিয় হৈ আছে',
    offline: 'অফলাইন',
    searchPlaceholder: 'ঘটনা, অস্বাভাৱিকতা, IP বিচাৰক...',
    simulateAttack: 'আক্ৰমণ অনুকৰণ কৰক',
    notifications: 'জাননীসমূহ',
    liveNotifLog: 'লাইভ জাননী লগ',
    clearAll: 'সকলো মচক',
    noNotif: 'কোনো নতুন জাননী নাই',
    teamName: 'উল্ফপেক স্কোৱাড্ৰন',
    hackName: 'নেক্সহেক 2.0',
    selectLanguage: 'ভাষা নিৰ্বাচন কৰক',
    searchLanguage: 'ভাষা বা দেশ বিচাৰক...',
    indianLanguages: 'ভাৰতীয় ভাষাসমূহ',
    internationalLanguages: 'আন্তঃৰাষ্ট্ৰীয় ভাষা',

    // Sidebar
    navDashboard: 'ডেশ্ববৰ্ড',
    navThreatAlerts: 'ভাবুকি ৰাডাৰ',
    navTraffic: 'ট্ৰেফিক বিশ্লেষণ',
    navWhatsApp: 'হোৱাটছএপ প্ৰেৰণ',
    navSimulator: 'আক্ৰমণ ছিমুলেটৰ',
    navAuditLogs: 'অডিট লগ',
    navSettings: 'ইঞ্জিন ছেটিংছ',

    // Metrics Grid
    metricTotalEvents: 'মুঠ টেলিমেট্ৰি ঘটনা',
    metricEventsSub: 'ৰিয়েল-টাইম স্লাইডিং উইণ্ডো টেলিমেট্ৰি',
    metricAnomalies: 'চিহ্নিত অস্বাভাৱিকতা',
    metricAnomaliesSub: 'হিউৰিষ্টিক স্পাইক ট্ৰিগাৰ',
    metricThreatLevel: 'সক্ৰিয় ভাবুকিৰ স্তৰ',
    metricThreatLevelSub: 'গতিশীল বেচলাইন মূল্যায়ন',
    metricWhatsApp: 'স্বয়ংক্ৰিয় হোৱাটছএপ বাৰ্তা',
    metricWhatsAppSub: 'সহজ ভাষাত ক্ষিপ্ৰ ম’বাইল সতৰ্কবাৰ্তা',
    statusNominal: 'টেলিমেট্ৰি স্বাভাৱিক',
    statusIncidents: 'সংকটজনক ঘটনা',
    statusStrict: 'কঠোৰ সুৰক্ষা',
    statusDispatched: 'ক্ষিপ্ৰ সতৰ্কতা',

    // Traffic Chart
    chartTitle: 'লাইভ টেলিমেট্ৰি ইনপুট বনাম অস্বাভাৱিকতা',
    chartSub: 'ৰিয়েল-টাইম স্লাইডিং উইণ্ডো ইভেন্ট পৰিমাণ',
    chartLegendIngestion: 'ইনপুট হাৰ (eps)',
    chartLegendAnomalies: 'অস্বাভাৱিকতাৰ সংখ্যা',
    tab15m: '15 মিনিট',
    tab1h: '1 ঘণ্টা',
    tab24h: '24 ঘণ্টা',
    filterAll: 'সম্পূৰ্ণ ট্ৰেফিক',
    filterAnomalies: 'কেৱল অস্বাভাৱিকতা',
    statPeakRate: 'সৰ্বাধিক ইনপুট হাৰ',
    statAnomalyRate: 'ৰিয়েল-টাইম অস্বাভাৱিকতা হাৰ',
    statWindow: 'উইণ্ডো সময়সীমা',
    statBaseline: 'বেচলাইন স্থিতি',
    baselineStable: 'সুস্থিৰ (12s)',

    // Threat Feed
    feedTitle: 'ৰিয়েল-টাইম থ্ৰেট ইন্টেলিজেন্স আৰু সহজ বিশ্লেষণ',
    feedSub: 'সহজ ভাষা অনুবাদৰ সৈতে টেলিমেট্ৰি ৰাডাৰ',
    feedLiveActive: 'লাইভ ষ্ট্ৰিম সক্ৰিয় হৈ আছে',
    filterAllAlerts: 'সকলো সতৰ্কবাৰ্তা',
    filterActive: 'সক্ৰিয়',
    filterCritical: 'সংকটজনক',
    filterResolved: 'সমাধান হ’ল',
    noAlertsFound: 'কোনো ঘটনা পোৱা নগ’ল।',
    takeRemediation: 'সুৰক্ষা পদক্ষেপ লওক',
    actionCompleted: 'ঘটনা সমাধান আৰু সুৰক্ষিত হ’ল',
    showTelemetry: 'ৰ টেলিমেট্ৰি চাওক',
    hideTelemetry: 'টেলিমেট্ৰি লুকুৱাওক',
    dispatchedToWhatsApp: 'হোৱাটছএপত প্ৰেৰণ কৰা হ’ল',
    dispatchedTo: 'প্ৰাপক:',

    // Hero Card
    heroBadge: 'সহজ ভাষাৰ ৰাডাৰ',
    heroTitle: 'স্বয়ংক্ৰিয় হোৱাটছএপ ভাবুকি পাইপলাইন',
    heroSub: 'অস্বাভাৱিকতা ধৰা পৰিলে ইঞ্জিনে সহজ ভাষাত হোৱাটছএপ যোগে সতৰ্কবাৰ্তা পঠিয়ায়।',
    heroActiveRecipient: 'সক্ৰিয় প্ৰাপক:',
    heroBtnTest: 'হোৱাটছএপ পৰীক্ষা কৰক',
    heroBtnSim: 'ছিমুলেটৰ আৰম্ভ কৰক',

    // General
    languageChangedToast: 'ভাষা সলনি কৰা হ’ল:',
    saveChanges: 'সংৰক্ষণ কৰক',
    cancel: 'বাতিল',
    close: 'বন্ধ কৰক',
  },
  ur: {
    // Nav & Brand
    aiRadar: 'AI SaaS رڈار',
    radarActive: 'رڈار فعال ہے',
    offline: 'آف لائن',
    searchPlaceholder: 'واقعات، بے قاعدگیاں، آئی پی، صارفین تلاش کریں...',
    simulateAttack: 'حملے کا نمونہ بنائیں',
    notifications: 'اطلاعات',
    liveNotifLog: 'لائیو اطلاعات لاگ',
    clearAll: 'سب صاف کریں',
    noNotif: 'کوئی نئی اطلاع نہیں ہے',
    teamName: 'ولف پیک اسکواڈرن',
    hackName: 'نیکس ہیک 2.0',
    selectLanguage: 'زبان منتخب کریں',
    searchLanguage: 'زبان یا ملک تلاش کریں...',
    indianLanguages: 'ہندوستانی زبانیں',
    internationalLanguages: 'بین الاقوامی زبانیں',

    // Sidebar
    navDashboard: 'ڈیش بورڈ',
    navThreatAlerts: 'خطرہ رڈار',
    navTraffic: 'ٹریفک کا تجزیہ',
    navWhatsApp: 'واٹس ایپ ڈسپیچ',
    navSimulator: 'حملہ سمیلیٹر',
    navAuditLogs: 'آڈٹ لاگز',
    navSettings: 'انجن کی ترتیبات',

    // Metrics Grid
    metricTotalEvents: 'کل ٹیلی میٹری واقعات',
    metricEventsSub: 'ریئل ٹائم سلائیڈنگ ونڈو ٹیلی میٹری',
    metricAnomalies: 'نشان زدہ بے قاعدگیاں',
    metricAnomaliesSub: 'ہیورسٹک اسپائک ٹرگرز',
    metricThreatLevel: 'فعال خطرے کی سطح',
    metricThreatLevelSub: 'متحرک بنیادی جائزہ',
    metricWhatsApp: 'خودکار واٹس ایپ پیغامات',
    metricWhatsAppSub: 'آسان زبان میں فوری موبائل انتباہات',
    statusNominal: 'ٹیلی میٹری نارمل',
    statusIncidents: 'سنگین واقعات',
    statusStrict: 'سخت حفاظتی ڈھال',
    statusDispatched: 'فوری انتباہات',

    // Traffic Chart
    chartTitle: 'لائیو ٹیلی میٹری ان پٹ بمقابلہ بے قاعدگی اسپائکس',
    chartSub: 'ریئل ٹائم سلائیڈنگ ونڈو ایونٹ والیوم',
    chartLegendIngestion: 'ان پٹ کی شرح (eps)',
    chartLegendAnomalies: 'بے قاعدگیوں کی تعداد',
    tab15m: '15 منٹ',
    tab1h: '1 گھنٹہ',
    tab24h: '24 گھنٹے',
    filterAll: 'تمام ٹریفک',
    filterAnomalies: 'صرف بے قاعدگیاں',
    statPeakRate: 'زیادہ سے زیادہ ان پٹ کی شرح',
    statAnomalyRate: 'ریئل ٹائم بے قاعدگی کی شرح',
    statWindow: 'ونڈو کا دورانیہ',
    statBaseline: 'بیس لائن کی حالت',
    baselineStable: 'مستحکم (12s)',

    // Threat Feed
    feedTitle: 'ریئل ٹائم تھریٹ انٹیلی جنس اور آسان تجزیہ',
    feedSub: 'آسان زبان میں ترجمے کے ساتھ خودکار رڈار',
    feedLiveActive: 'لائیو اسٹریم فعال ہے',
    filterAllAlerts: 'تمام انتباہات',
    filterActive: 'فعال',
    filterCritical: 'انتہائی سنگین',
    filterResolved: 'حل ہو گیا',
    noAlertsFound: 'کوئی واقعہ نہیں ملا۔',
    takeRemediation: 'حفاظتی کارروائی کریں',
    actionCompleted: 'واقعہ حل ہو گیا اور محفوظ ہے',
    showTelemetry: 'را ٹیلی میٹری دیکھیں',
    hideTelemetry: 'ٹیلی میٹری چھپائیں',
    dispatchedToWhatsApp: 'واٹس ایپ پر بھیج دیا گیا',
    dispatchedTo: 'وصول کنندہ:',

    // Hero Card
    heroBadge: 'آسان زبان کا رڈار',
    heroTitle: 'خودکار واٹس ایپ تھریٹ پائپ لائن',
    heroSub: 'بے قاعدگی پر انجن آسان انتباہ واٹس ایپ کے ذریعے فوری بھیجتا ہے۔',
    heroActiveRecipient: 'فعال وصول کنندہ:',
    heroBtnTest: 'واٹس ایپ ٹیسٹ کریں',
    heroBtnSim: 'سمیلیٹر شروع کریں',

    // General
    languageChangedToast: 'زبان تبدیل کر کے کر دی گئی:',
    saveChanges: 'تبدیلیاں محفوظ کریں',
    cancel: 'منسوخ کریں',
    close: 'بند کریں',
  },
  es: {
    // Nav & Brand
    aiRadar: 'Radar IA SaaS',
    radarActive: 'Radar Activo',
    offline: 'Desconectado',
    searchPlaceholder: 'Buscar incidentes, anomalías, IPs, usuarios...',
    simulateAttack: 'Simular Ataque',
    notifications: 'Notificaciones',
    liveNotifLog: 'Registro de Notificaciones en Vivo',
    clearAll: 'Borrar todo',
    noNotif: 'No hay notificaciones nuevas',
    teamName: 'WolfPack Squadron',
    hackName: 'NexHack 2.0',
    selectLanguage: 'Seleccionar Idioma',
    searchLanguage: 'Buscar idioma o país...',
    indianLanguages: 'Idiomas Indios',
    internationalLanguages: 'Internacional',

    // Sidebar
    navDashboard: 'Panel',
    navThreatAlerts: 'Radar de Amenazas',
    navTraffic: 'Análisis de Tráfico',
    navWhatsApp: 'Envío de WhatsApp',
    navSimulator: 'Simulador de Ataques',
    navAuditLogs: 'Registros de Auditoría',
    navSettings: 'Configuración del Motor',

    // Metrics Grid
    metricTotalEvents: 'Eventos Totales de Ingesta',
    metricEventsSub: 'Telemetría de ventana deslizante en tiempo real',
    metricAnomalies: 'Anomalías Marcadas',
    metricAnomaliesSub: 'Activadores heurísticos y picos',
    metricThreatLevel: 'Nivel de Amenaza Activo',
    metricThreatLevelSub: 'Evaluación de línea base dinámica',
    metricWhatsApp: 'Envíos Autónomos de WhatsApp',
    metricWhatsAppSub: 'Alertas sin tecnicismos enviadas',
    statusNominal: 'Telemetría Nominal',
    statusIncidents: 'Incidentes Críticos',
    statusStrict: 'Escudo Estricto',
    statusDispatched: 'Alertas Instantáneas',

    // Traffic Chart
    chartTitle: 'Ingesta de Telemetría en Vivo vs Picos de Anomalías',
    chartSub: 'Volumen de eventos en tiempo real con picos de anomalías heurísticas',
    chartLegendIngestion: 'Ingesta (eps)',
    chartLegendAnomalies: 'Anomalías (conteo)',
    tab15m: '15 Minutos',
    tab1h: '1 Hora',
    tab24h: '24 Horas',
    filterAll: 'Todo el Tráfico',
    filterAnomalies: 'Solo Anomalías',
    statPeakRate: 'Tasa Máxima de Ingesta',
    statAnomalyRate: 'Tasa de Anomalías en Tiempo Real',
    statWindow: 'Duración de la Ventana',
    statBaseline: 'Estado de la Línea Base',
    baselineStable: 'ESTABLE (12s)',

    // Threat Feed
    feedTitle: 'Inteligencia de Amenazas en Tiempo Real y Síntesis sin Tecnicismos',
    feedSub: 'Radar de telemetría de ventana deslizante con traducción instantánea a lenguaje natural',
    feedLiveActive: 'TRANSMISIÓN EN VIVO ACTIVA',
    filterAllAlerts: 'Todas las Alertas',
    filterActive: 'Activas',
    filterCritical: 'Críticas',
    filterResolved: 'Resueltas',
    noAlertsFound: 'Ningún incidente coincide con su búsqueda.',
    takeRemediation: 'Tomar Acción de Mitigación',
    actionCompleted: 'Incidente Resuelto y Protegido',
    showTelemetry: 'Ver Telemetría Cruda',
    hideTelemetry: 'Ocultar Telemetría',
    dispatchedToWhatsApp: 'Enviado a WhatsApp',
    dispatchedTo: 'Enviado a',

    // Hero Card
    heroBadge: 'RADAR SIN TECNICISMOS',
    heroTitle: 'Canal Autónomo de Amenazas por WhatsApp',
    heroSub: 'Cuando la ventana deslizante detecta una anomalía, nuestro motor crea alertas móviles en lenguaje claro y las envía al instante a los operadores por WhatsApp API.',
    heroActiveRecipient: 'Destinatario Activo:',
    heroBtnTest: 'Probar Envío por WhatsApp',
    heroBtnSim: 'Ejecutar Simulador',

    // General
    languageChangedToast: 'Idioma cambiado a',
    saveChanges: 'Guardar Cambios',
    cancel: 'Cancelar',
    close: 'Cerrar',
  },
  fr: {
    // Nav & Brand
    aiRadar: 'Radar IA SaaS',
    radarActive: 'Radar Actif',
    offline: 'Hors ligne',
    searchPlaceholder: 'Rechercher incidents, anomalies, IP, utilisateurs...',
    simulateAttack: 'Simuler une Attaque',
    notifications: 'Notifications',
    liveNotifLog: 'Journal des Notifications en Direct',
    clearAll: 'Tout effacer',
    noNotif: 'Aucune nouvelle notification',
    teamName: 'WolfPack Squadron',
    hackName: 'NexHack 2.0',
    selectLanguage: 'Choisir la Langue',
    searchLanguage: 'Rechercher une langue ou un pays...',
    indianLanguages: 'Langues Indiennes',
    internationalLanguages: 'International',

    // Sidebar
    navDashboard: 'Tableau de Bord',
    navThreatAlerts: 'Radar des Menaces',
    navTraffic: 'Analyse du Trafic',
    navWhatsApp: 'Envoi WhatsApp',
    navSimulator: 'Simulateur d\'Attaque',
    navAuditLogs: 'Journaux d\'Audit',
    navSettings: 'Paramètres Moteur',

    // Metrics Grid
    metricTotalEvents: 'Total des Événements Ingérés',
    metricEventsSub: 'Télémétrie en temps réel par fenêtre glissante',
    metricAnomalies: 'Anomalies Signalées',
    metricAnomaliesSub: 'Déclencheurs heuristiques et pics',
    metricThreatLevel: 'Niveau de Menace Actif',
    metricThreatLevelSub: 'Évaluation dynamique de référence',
    metricWhatsApp: 'Envois Autonomes WhatsApp',
    metricWhatsAppSub: 'Alertes en langage clair transmises',
    statusNominal: 'Télémétrie Nominale',
    statusIncidents: 'Incidents Critiques',
    statusStrict: 'Bouclier Strict',
    statusDispatched: 'Alertes Instantanées',

    // Traffic Chart
    chartTitle: 'Ingestion de Télémétrie en Direct vs Pics d\'Anomalies',
    chartSub: 'Volume d\'événements en temps réel avec pics d\'anomalies heuristiques',
    chartLegendIngestion: 'Ingestion (eps)',
    chartLegendAnomalies: 'Anomalies (nombre)',
    tab15m: '15 Minutes',
    tab1h: '1 Heure',
    tab24h: '24 Heures',
    filterAll: 'Tout le Trafic',
    filterAnomalies: 'Anomalies Uniquement',
    statPeakRate: 'Taux d\'Ingestion de Pointe',
    statAnomalyRate: 'Taux d\'Anomalie en Temps Réel',
    statWindow: 'Durée de la Fenêtre',
    statBaseline: 'État de Référence',
    baselineStable: 'STABLE (12s)',

    // Threat Feed
    feedTitle: 'Renseignement sur les Menaces en Temps Réel et Synthèse Claire',
    feedSub: 'Radar de télémétrie avec traduction instantanée en langage naturel sans jargon',
    feedLiveActive: 'FLUX EN DIRECT ACTIF',
    filterAllAlerts: 'Toutes les Alertes',
    filterActive: 'Actives',
    filterCritical: 'Critiques',
    filterResolved: 'Résolues',
    noAlertsFound: 'Aucun incident ne correspond à votre recherche.',
    takeRemediation: 'Appliquer la Mesure Corrective',
    actionCompleted: 'Incident Résolu et Protégé',
    showTelemetry: 'Voir Télémétrie Brute',
    hideTelemetry: 'Masquer Télémétrie',
    dispatchedToWhatsApp: 'Transmis sur WhatsApp',
    dispatchedTo: 'Transmis à',

    // Hero Card
    heroBadge: 'RADAR SANS JARGON',
    heroTitle: 'Pipeline de Menace Autonome WhatsApp',
    heroSub: 'Lorsqu\'une anomalie est détectée, notre moteur génère des alertes mobiles en langage clair et les transmet instantanément aux opérateurs via l\'API WhatsApp.',
    heroActiveRecipient: 'Destinataire Actif :',
    heroBtnTest: 'Tester l\'Envoi WhatsApp',
    heroBtnSim: 'Lancer le Simulateur',

    // General
    languageChangedToast: 'Langue modifiée en',
    saveChanges: 'Enregistrer les Modifications',
    cancel: 'Annuler',
    close: 'Fermer',
  },
  de: {
    // Nav & Brand
    aiRadar: 'KI SaaS Radar',
    radarActive: 'Radar Aktiv',
    offline: 'Offline',
    searchPlaceholder: 'Vorfälle, Anomalien, IPs, Benutzer suchen...',
    simulateAttack: 'Angriff Simulieren',
    notifications: 'Benachrichtigungen',
    liveNotifLog: 'Live-Benachrichtigungsprotokoll',
    clearAll: 'Alles löschen',
    noNotif: 'Keine neuen Benachrichtigungen',
    teamName: 'WolfPack Squadron',
    hackName: 'NexHack 2.0',
    selectLanguage: 'Sprache Wählen',
    searchLanguage: 'Sprache oder Land suchen...',
    indianLanguages: 'Indische Sprachen',
    internationalLanguages: 'International',

    // Sidebar
    navDashboard: 'Dashboard',
    navThreatAlerts: 'Bedrohungsradar',
    navTraffic: 'Traffic-Analyse',
    navWhatsApp: 'WhatsApp-Versand',
    navSimulator: 'Angriffs-Simulator',
    navAuditLogs: 'Audit-Protokolle',
    navSettings: 'Engine-Einstellungen',

    // Metrics Grid
    metricTotalEvents: 'Gesamte Ingestion-Ereignisse',
    metricEventsSub: 'Echtzeit-Gleitfenster-Telemetrie',
    metricAnomalies: 'Erkannte Anomalien',
    metricAnomaliesSub: 'Heuristische & Spitzen-Trigger',
    metricThreatLevel: 'Aktives Bedrohungslevel',
    metricThreatLevelSub: 'Dynamische Baseline-Bewertung',
    metricWhatsApp: 'Autonome WhatsApp-Versendungen',
    metricWhatsAppSub: 'Verständliche Mobile-Alerts übermittelt',
    statusNominal: 'Telemetrie Nominal',
    statusIncidents: 'Kritische Vorfälle',
    statusStrict: 'Strikter Schild',
    statusDispatched: 'Sofortige Alerts',

    // Traffic Chart
    chartTitle: 'Live-Telemetrie-Ingestion vs. Anomalie-Spitzen',
    chartSub: 'Echtzeit-Ereignisvolumen mit heuristischen Anomalie-Spitzen',
    chartLegendIngestion: 'Ingestion (eps)',
    chartLegendAnomalies: 'Anomalien (Anzahl)',
    tab15m: '15 Minuten',
    tab1h: '1 Stunde',
    tab24h: '24 Stunden',
    filterAll: 'Gesamter Traffic',
    filterAnomalies: 'Nur Anomalien',
    statPeakRate: 'Spitzen-Ingestionsrate',
    statAnomalyRate: 'Echtzeit-Anomalierate',
    statWindow: 'Fensterdauer',
    statBaseline: 'Baseline-Status',
    baselineStable: 'STABIL (12s)',

    // Threat Feed
    feedTitle: 'Echtzeit-Bedrohungsanalyse & Verständliche Zusammenfassung',
    feedSub: 'Autonomes Gleitfenster-Radar mit sofortiger Übersetzung in natürliche Sprache',
    feedLiveActive: 'LIVE-STREAM AKTIV',
    filterAllAlerts: 'Alle Alerts',
    filterActive: 'Aktiv',
    filterCritical: 'Kritisch',
    filterResolved: 'Gelöst',
    noAlertsFound: 'Keine Vorfälle stimmen mit Ihrer Suche überein.',
    takeRemediation: 'Schutzmaßnahme Ergreifen',
    actionCompleted: 'Vorfall Gelöst & Geschützt',
    showTelemetry: 'Roh-Telemetrie Anzeigen',
    hideTelemetry: 'Telemetrie Ausblenden',
    dispatchedToWhatsApp: 'Über WhatsApp versendet',
    dispatchedTo: 'Versendet an',

    // Hero Card
    heroBadge: 'RADAR OHNE FACHJARGON',
    heroTitle: 'Autonome WhatsApp-Bedrohungspipeline',
    heroSub: 'Wird eine Anomalie festgestellt, erstellt die Engine verständliche Alerts und sendet sie sofort per WhatsApp-API an Operatoren.',
    heroActiveRecipient: 'Aktiver Empfänger:',
    heroBtnTest: 'WhatsApp-Versand Testen',
    heroBtnSim: 'Simulator Starten',

    // General
    languageChangedToast: 'Sprache geändert auf',
    saveChanges: 'Änderungen Speichern',
    cancel: 'Abbrechen',
    close: 'Schließen',
  },
  ja: {
    // Nav & Brand
    aiRadar: 'AI SaaS レーダー',
    radarActive: 'レーダー稼働中',
    offline: 'オフライン',
    searchPlaceholder: 'インシデント、異常、IP、ユーザーを検索...',
    simulateAttack: '攻撃シミュレーション',
    notifications: '通知',
    liveNotifLog: 'リアルタイム通知ログ',
    clearAll: 'すべて消去',
    noNotif: '新しい通知はありません',
    teamName: 'WolfPack Squadron',
    hackName: 'NexHack 2.0',
    selectLanguage: '言語を選択',
    searchLanguage: '言語または国を検索...',
    indianLanguages: 'インドの諸言語',
    internationalLanguages: '国際言語',

    // Sidebar
    navDashboard: 'ダッシュボード',
    navThreatAlerts: '脅威レーダー',
    navTraffic: 'トラフィック分析',
    navWhatsApp: 'WhatsApp 配信',
    navSimulator: '攻撃シミュレーター',
    navAuditLogs: '監査ログ',
    navSettings: 'エンジン設定',

    // Metrics Grid
    metricTotalEvents: '総テレメトリ受信イベント',
    metricEventsSub: 'リアルタイム スライディング ウィンドウ テレメトリ',
    metricAnomalies: '検出された異常',
    metricAnomaliesSub: 'ヒューリスティックおよびスパイク トリガー',
    metricThreatLevel: '現在の脅威レベル',
    metricThreatLevelSub: '動的ベースライン評価',
    metricWhatsApp: '自律 WhatsApp 配信',
    metricWhatsAppSub: '平易な言語での即時アラート送信',
    statusNominal: 'テレメトリ正常',
    statusIncidents: '重大なインシデント',
    statusStrict: '厳重防御中',
    statusDispatched: '即時アラート',

    // Traffic Chart
    chartTitle: 'リアルタイム テレメトリ受信 vs 異常スパイク',
    chartSub: 'ヒューリスティック異常スパイクを伴うスライディング ウィンドウ イベント量',
    chartLegendIngestion: '受信レート (eps)',
    chartLegendAnomalies: '異常数',
    tab15m: '15分',
    tab1h: '1時間',
    tab24h: '24時間',
    filterAll: '全トラフィック',
    filterAnomalies: '異常のみ',
    statPeakRate: 'ピーク受信レート',
    statAnomalyRate: 'リアルタイム異常レート',
    statWindow: 'ウィンドウ期間',
    statBaseline: 'ベースライン状態',
    baselineStable: '安定 (12s)',

    // Threat Feed
    feedTitle: 'リアルタイム脅威インテリジェンスと分かりやすい分析',
    feedSub: '平易な自然言語変換を備えた自律スライディング ウィンドウ レーダー',
    feedLiveActive: 'ライブ ストリーム稼働中',
    filterAllAlerts: 'すべてのアラート',
    filterActive: '対応中',
    filterCritical: '重大',
    filterResolved: '解決済み',
    noAlertsFound: '検索条件に一致するインシデントはありません。',
    takeRemediation: '修復アクションを実行',
    actionCompleted: 'インシデント解決・保護完了',
    showTelemetry: '生テレメトリを表示',
    hideTelemetry: 'テレメトリを非表示',
    dispatchedToWhatsApp: 'WhatsApp へ送信済み',
    dispatchedTo: '送信先:',

    // Hero Card
    heroBadge: '専門用語不要レーダー',
    heroTitle: '自律型 WhatsApp 脅威パイプライン',
    heroSub: '異常が検出されると、エンジンが誰にでも分かる平易なアラートを作成し、WhatsApp API を通じて即座に送信します。',
    heroActiveRecipient: '受信先:',
    heroBtnTest: 'WhatsApp 送信テスト',
    heroBtnSim: 'シミュレーター実行',

    // General
    languageChangedToast: '言語を変更しました:',
    saveChanges: '変更を保存',
    cancel: 'キャンセル',
    close: '閉じる',
  },
  zh: {
    // Nav & Brand
    aiRadar: 'AI SaaS 雷达',
    radarActive: '雷达运行中',
    offline: '离线',
    searchPlaceholder: '搜索事件、异常、IP、用户...',
    simulateAttack: '模拟攻击',
    notifications: '通知',
    liveNotifLog: '实时通知日志',
    clearAll: '清除全部',
    noNotif: '暂无新通知',
    teamName: 'WolfPack Squadron',
    hackName: 'NexHack 2.0',
    selectLanguage: '选择语言',
    searchLanguage: '搜索语言或国家...',
    indianLanguages: '印度语言',
    internationalLanguages: '国际语言',

    // Sidebar
    navDashboard: '仪表板',
    navThreatAlerts: '威胁雷达',
    navTraffic: '流量分析',
    navWhatsApp: 'WhatsApp 调度',
    navSimulator: '攻击模拟器',
    navAuditLogs: '审计日志',
    navSettings: '引擎设置',

    // Metrics Grid
    metricTotalEvents: '总摄取事件',
    metricEventsSub: '实时滑动窗口遥测',
    metricAnomalies: '标记的异常',
    metricAnomaliesSub: '启发式与尖峰触发器',
    metricThreatLevel: '当前威胁等级',
    metricThreatLevelSub: '动态基线评估',
    metricWhatsApp: '自主 WhatsApp 发送',
    metricWhatsAppSub: '即时零术语手机告警',
    statusNominal: '遥测正常',
    statusIncidents: '严重事件',
    statusStrict: '严格防护',
    statusDispatched: '即时告警',

    // Traffic Chart
    chartTitle: '实时遥测摄取 vs 异常突发',
    chartSub: '带启发式异常尖峰的实时滑动窗口事件量',
    chartLegendIngestion: '摄取速率 (eps)',
    chartLegendAnomalies: '异常数量',
    tab15m: '15分钟',
    tab1h: '1小时',
    tab24h: '24小时',
    filterAll: '全部流量',
    filterAnomalies: '仅异常',
    statPeakRate: '峰值摄取率',
    statAnomalyRate: '实时异常率',
    statWindow: '窗口持续时间',
    statBaseline: '基线状态',
    baselineStable: '稳定 (12s)',

    // Threat Feed
    feedTitle: '实时威胁情报与通俗语言分析',
    feedSub: '具备自然语言即时翻译的自主滑动窗口遥测雷达',
    feedLiveActive: '实时数据流活跃',
    filterAllAlerts: '全部告警',
    filterActive: '活跃中',
    filterCritical: '极严重',
    filterResolved: '已解决',
    noAlertsFound: '未找到符合搜索条件的事件。',
    takeRemediation: '采取修复措施',
    actionCompleted: '事件已解决并受保护',
    showTelemetry: '查看原始遥测',
    hideTelemetry: '隐藏遥测',
    dispatchedToWhatsApp: '已发送至 WhatsApp',
    dispatchedTo: '发送至:',

    // Hero Card
    heroBadge: '零术语雷达',
    heroTitle: '自主 WhatsApp 威胁管道',
    heroSub: '当滑动窗口标记异常时，引擎会生成清晰明了的手机告警，并通过 WhatsApp API 即时发送给运维人员。',
    heroActiveRecipient: '当前接收人:',
    heroBtnTest: '测试 WhatsApp 发送',
    heroBtnSim: '启动模拟器',

    // General
    languageChangedToast: '语言已切换为:',
    saveChanges: '保存更改',
    cancel: '取消',
    close: '关闭',
  },
  ar: {
    // Nav & Brand
    aiRadar: 'رادار الذكاء الاصطناعي',
    radarActive: 'الرادار نشط',
    offline: 'غير متصل',
    searchPlaceholder: 'ابحث عن الحوادث، الشذوذ، العناوين، المستخدمين...',
    simulateAttack: 'محاكاة الهجوم',
    notifications: 'الإشعارات',
    liveNotifLog: 'سجل الإشعارات المباشر',
    clearAll: 'مسح الكل',
    noNotif: 'لا توجد إشعارات جديدة',
    teamName: 'سرب ولف باك',
    hackName: 'نيكس هاك 2.0',
    selectLanguage: 'اختر اللغة',
    searchLanguage: 'ابحث عن لغة أو دولة...',
    indianLanguages: 'اللغات الهندية',
    internationalLanguages: 'اللغات الدولية',

    // Sidebar
    navDashboard: 'لوحة التحكم',
    navThreatAlerts: 'رادار التهديدات',
    navTraffic: 'تحليلات حركة المرور',
    navWhatsApp: 'إرسال واتساب',
    navSimulator: 'محاكي الهجمات',
    navAuditLogs: 'سجلات التدقيق',
    navSettings: 'إعدادات المحرك',

    // Metrics Grid
    metricTotalEvents: 'إجمالي أحداث القياس',
    metricEventsSub: 'قياس النافذة المنزلقة في الوقت الفعلي',
    metricAnomalies: 'الشذوذ المكتشف',
    metricAnomaliesSub: 'محفزات الارتفاعات الإرشادية',
    metricThreatLevel: 'مستوى التهديد النشط',
    metricThreatLevelSub: 'تقييم خط الأساس الديناميكي',
    metricWhatsApp: 'إرسال واتساب التلقائي',
    metricWhatsAppSub: 'تنبيهات فورية بدون تعقيدات تقنية',
    statusNominal: 'القياس طبيعي',
    statusIncidents: 'حوادث حرجة',
    statusStrict: 'درع صارم',
    statusDispatched: 'تنبيهات فورية',

    // Traffic Chart
    chartTitle: 'حجم القياس المباشر مقابل ارتفاعات الشذوذ',
    chartSub: 'حجم أحداث النافذة المنزلقة في الوقت الفعلي',
    chartLegendIngestion: 'معدل الاستيعاب (eps)',
    chartLegendAnomalies: 'عدد الشذوذ',
    tab15m: '15 دقيقة',
    tab1h: 'ساعة واحدة',
    tab24h: '24 ساعة',
    filterAll: 'كافة البيانات',
    filterAnomalies: 'الشذوذ فقط',
    statPeakRate: 'أعلى معدل استيعاب',
    statAnomalyRate: 'معدل الشذوذ اللحظي',
    statWindow: 'مدة النافذة',
    statBaseline: 'حالة خط الأساس',
    baselineStable: 'مستقر (12s)',

    // Threat Feed
    feedTitle: 'استخبارات التهديدات اللحظية والتحليل المبسط',
    feedSub: 'رادار القياس التلقائي مع ترجمة فورية بلغة واضحة',
    feedLiveActive: 'البث المباشر نشط',
    filterAllAlerts: 'كافة التنبيهات',
    filterActive: 'نشط',
    filterCritical: 'حرج للغاية',
    filterResolved: 'تم الحل',
    noAlertsFound: 'لم يتم العثور على أي حوادث مطابقة.',
    takeRemediation: 'اتخاذ إجراء الحماية',
    actionCompleted: 'تم حل الحادث وحمايته',
    showTelemetry: 'عرض بيانات القياس الخام',
    hideTelemetry: 'إخفاء البيانات',
    dispatchedToWhatsApp: 'تم الإرسال عبر واتساب',
    dispatchedTo: 'المرسل إليه:',

    // Hero Card
    heroBadge: 'رادار بلغة مبسطة',
    heroTitle: 'قناة تهديدات واتساب الذاتية',
    heroSub: 'عند رصد أي سلوك مريب، ينشئ النظام تنبيهاً بلغة بسيطة ويرسله فوراً عبر واتساب.',
    heroActiveRecipient: 'المستلم النشط:',
    heroBtnTest: 'اختبار إرسال واتساب',
    heroBtnSim: 'تشغيل المحاكي',

    // General
    languageChangedToast: 'تم تغيير اللغة إلى:',
    saveChanges: 'حفظ التغييرات',
    cancel: 'إلغاء',
    close: 'إغلاق',
  },
  ru: {
    // Nav & Brand
    aiRadar: 'ИИ SaaS Радар',
    radarActive: 'Радар Активен',
    offline: 'Офлайн',
    searchPlaceholder: 'Поиск инцидентов, аномалий, IP, пользователей...',
    simulateAttack: 'Симулировать Атаку',
    notifications: 'Уведомления',
    liveNotifLog: 'Журнал уведомлений в реальном времени',
    clearAll: 'Очистить всё',
    noNotif: 'Нет новых уведомлений',
    teamName: 'WolfPack Squadron',
    hackName: 'NexHack 2.0',
    selectLanguage: 'Выбрать Язык',
    searchLanguage: 'Поиск языка или страны...',
    indianLanguages: 'Языки Индии',
    internationalLanguages: 'Международные языки',

    // Sidebar
    navDashboard: 'Панель',
    navThreatAlerts: 'Радар Угроз',
    navTraffic: 'Анализ Трафика',
    navWhatsApp: 'WhatsApp Рассылка',
    navSimulator: 'Симулятор Атак',
    navAuditLogs: 'Журналы Аудита',
    navSettings: 'Настройки Движка',

    // Metrics Grid
    metricTotalEvents: 'Всего Событий Телеметрии',
    metricEventsSub: 'Телеметрия скользящего окна в реальном времени',
    metricAnomalies: 'Выявленные Аномалии',
    metricAnomaliesSub: 'Эвристические триггеры и всплески',
    metricThreatLevel: 'Текущий Уровень Угрозы',
    metricThreatLevelSub: 'Динамическая оценка базового уровня',
    metricWhatsApp: 'Автономные Отправки WhatsApp',
    metricWhatsAppSub: 'Понятные мобильные оповещения отправлены',
    statusNominal: 'Телеметрия в норме',
    statusIncidents: 'Критические инциденты',
    statusStrict: 'Строгий щит',
    statusDispatched: 'Мгновенные оповещения',

    // Traffic Chart
    chartTitle: 'Поток Телеметрии vs Всплески Аномалий',
    chartSub: 'Объем событий скользящего окна с эвристическими всплесками',
    chartLegendIngestion: 'Скорость ввода (eps)',
    chartLegendAnomalies: 'Количество аномалий',
    tab15m: '15 минут',
    tab1h: '1 час',
    tab24h: '24 часа',
    filterAll: 'Весь трафик',
    filterAnomalies: 'Только аномалии',
    statPeakRate: 'Пиковая скорость ввода',
    statAnomalyRate: 'Частота аномалий в реальном времени',
    statWindow: 'Длительность окна',
    statBaseline: 'Базовый статус',
    baselineStable: 'СТАБИЛЬНО (12s)',

    // Threat Feed
    feedTitle: 'Аналитика Угроз и Понятный Анализ в Реальном Времени',
    feedSub: 'Автономный радар с мгновенным переводом на понятный человеческий язык',
    feedLiveActive: 'ПРЯМОЙ ЭФИР АКТИВЕН',
    filterAllAlerts: 'Все оповещения',
    filterActive: 'Активные',
    filterCritical: 'Критические',
    filterResolved: 'Решенные',
    noAlertsFound: 'По вашему запросу инцидентов не найдено.',
    takeRemediation: 'Принять Меры Защиты',
    actionCompleted: 'Инцидент Устранен и Защищен',
    showTelemetry: 'Показать сырую телеметрию',
    hideTelemetry: 'Скрыть телеметрию',
    dispatchedToWhatsApp: 'Отправлено в WhatsApp',
    dispatchedTo: 'Отправлено на',

    // Hero Card
    heroBadge: 'РАДАР БЕЗ ЖАРГОНА',
    heroTitle: 'Автономный Канал Угроз WhatsApp',
    heroSub: 'При обнаружении аномалии движок формирует понятное мобильное оповещение и мгновенно отправляет его операторам через WhatsApp API.',
    heroActiveRecipient: 'Активный получатель:',
    heroBtnTest: 'Тест отправки WhatsApp',
    heroBtnSim: 'Запустить симулятор',

    // General
    languageChangedToast: 'Язык изменен на:',
    saveChanges: 'Сохранить изменения',
    cancel: 'Отмена',
    close: 'Закрыть',
  },
  pt: {
    // Nav & Brand
    aiRadar: 'Radar IA SaaS',
    radarActive: 'Radar Ativo',
    offline: 'Offline',
    searchPlaceholder: 'Pesquisar incidentes, anomalias, IPs, usuários...',
    simulateAttack: 'Simular Ataque',
    notifications: 'Notificações',
    liveNotifLog: 'Log de Notificações em Tempo Real',
    clearAll: 'Limpar tudo',
    noNotif: 'Nenhuma nova notificação',
    teamName: 'WolfPack Squadron',
    hackName: 'NexHack 2.0',
    selectLanguage: 'Selecionar Idioma',
    searchLanguage: 'Pesquisar idioma ou país...',
    indianLanguages: 'Idiomas Indianos',
    internationalLanguages: 'Internacional',

    // Sidebar
    navDashboard: 'Painel',
    navThreatAlerts: 'Radar de Ameaças',
    navTraffic: 'Análise de Tráfego',
    navWhatsApp: 'Envio WhatsApp',
    navSimulator: 'Simulador de Ataques',
    navAuditLogs: 'Logs de Auditoria',
    navSettings: 'Configurações do Motor',

    // Metrics Grid
    metricTotalEvents: 'Total de Eventos Ingeridos',
    metricEventsSub: 'Telemetria de janela deslizante em tempo real',
    metricAnomalies: 'Anomalias Sinalizadas',
    metricAnomaliesSub: 'Gatilhos heurísticos e picos',
    metricThreatLevel: 'Nível de Ameaça Ativo',
    metricThreatLevelSub: 'Avaliação dinâmica da linha de base',
    metricWhatsApp: 'Envios Autônomos por WhatsApp',
    metricWhatsAppSub: 'Alertas sem jargões transmitidos',
    statusNominal: 'Telemetria Nominal',
    statusIncidents: 'Incidentes Críticos',
    statusStrict: 'Escudo Estrito',
    statusDispatched: 'Alertas Instantâneos',

    // Traffic Chart
    chartTitle: 'Ingestão de Telemetria ao Vivo vs Picos de Anomalias',
    chartSub: 'Volume de eventos com picos de anomalias heurísticas',
    chartLegendIngestion: 'Ingestão (eps)',
    chartLegendAnomalies: 'Anomalias (contagem)',
    tab15m: '15 Minutos',
    tab1h: '1 Hora',
    tab24h: '24 Horas',
    filterAll: 'Todo o Tráfego',
    filterAnomalies: 'Apenas Anomalias',
    statPeakRate: 'Taxa Máxima de Ingestão',
    statAnomalyRate: 'Taxa de Anomalias em Tempo Real',
    statWindow: 'Duração da Janela',
    statBaseline: 'Status da Linha de Base',
    baselineStable: 'ESTÁVEL (12s)',

    // Threat Feed
    feedTitle: 'Inteligência de Ameaças em Tempo Real e Síntese Clara',
    feedSub: 'Radar de telemetria com tradução instantânea para linguagem natural',
    feedLiveActive: 'TRANSMISSÃO AO VIVO ATIVA',
    filterAllAlerts: 'Todos os Alertas',
    filterActive: 'Ativos',
    filterCritical: 'Críticos',
    filterResolved: 'Resolvidos',
    noAlertsFound: 'Nenhum incidente encontrado.',
    takeRemediation: 'Tomar Ação Corretiva',
    actionCompleted: 'Incidente Resolvido e Protegido',
    showTelemetry: 'Ver Telemetria Bruta',
    hideTelemetry: 'Ocultar Telemetria',
    dispatchedToWhatsApp: 'Enviado para WhatsApp',
    dispatchedTo: 'Enviado para',

    // Hero Card
    heroBadge: 'RADAR SEM JARGÕES',
    heroTitle: 'Pipeline Autônomo de Ameaças por WhatsApp',
    heroSub: 'Quando uma anomalia é detectada, o motor cria alertas móveis claros e os envia instantaneamente aos operadores via API do WhatsApp.',
    heroActiveRecipient: 'Destinatário Ativo:',
    heroBtnTest: 'Testar Envio por WhatsApp',
    heroBtnSim: 'Iniciar Simulador',

    // General
    languageChangedToast: 'Idioma alterado para:',
    saveChanges: 'Salvar Alterações',
    cancel: 'Cancelar',
    close: 'Fechar',
  },
  ko: {
    // Nav & Brand
    aiRadar: 'AI SaaS 레이더',
    radarActive: '레이더 활성화됨',
    offline: '오프라인',
    searchPlaceholder: '사고, 이상 징후, IP, 사용자 검색...',
    simulateAttack: '공격 시뮬레이션',
    notifications: '알림',
    liveNotifLog: '실시간 알림 로그',
    clearAll: '모두 지우기',
    noNotif: '새 알림 없음',
    teamName: 'WolfPack Squadron',
    hackName: 'NexHack 2.0',
    selectLanguage: '언어 선택',
    searchLanguage: '언어 또는 국가 검색...',
    indianLanguages: '인도 언어',
    internationalLanguages: '국제 언어',

    // Sidebar
    navDashboard: '대시보드',
    navThreatAlerts: '위협 레이더',
    navTraffic: '트래픽 분석',
    navWhatsApp: 'WhatsApp 전송',
    navSimulator: '공격 시뮬레이터',
    navAuditLogs: '감사 로그',
    navSettings: '엔진 설정',

    // Metrics Grid
    metricTotalEvents: '총 수집 이벤트',
    metricEventsSub: '실시간 슬라이딩 윈도우 원격 측정',
    metricAnomalies: '감지된 이상 징후',
    metricAnomaliesSub: '휴리스틱 및 스파이크 트리거',
    metricThreatLevel: '활성 위협 수준',
    metricThreatLevelSub: '동적 기준선 평가',
    metricWhatsApp: '자율 WhatsApp 전송',
    metricWhatsAppSub: '알기 쉬운 모바일 경보 즉시 전송',
    statusNominal: '원격 측정 정상',
    statusIncidents: '심각한 사고',
    statusStrict: '엄격한 방어',
    statusDispatched: '즉시 경보',

    // Traffic Chart
    chartTitle: '실시간 원격 측정 수집 vs 이상 스파이크',
    chartSub: '휴리스틱 이상 징후가 포함된 실시간 이벤트 볼륨',
    chartLegendIngestion: '수집률 (eps)',
    chartLegendAnomalies: '이상 수',
    tab15m: '15분',
    tab1h: '1시간',
    tab24h: '24시간',
    filterAll: '전체 트래픽',
    filterAnomalies: '이상 징후만',
    statPeakRate: '최대 수집률',
    statAnomalyRate: '실시간 이상 발생률',
    statWindow: '윈도우 지속 시간',
    statBaseline: '기준선 상태',
    baselineStable: '안정 (12s)',

    // Threat Feed
    feedTitle: '실시간 위협 인텔리전스 및 쉬운 분석',
    feedSub: '자연어 즉시 번역을 지원하는 자율 슬라이딩 윈도우 레이더',
    feedLiveActive: '실시간 스트림 활성화',
    filterAllAlerts: '모든 알림',
    filterActive: '활성',
    filterCritical: '심각',
    filterResolved: '해결됨',
    noAlertsFound: '검색 조건과 일치하는 사고가 없습니다.',
    takeRemediation: '보안 조치 실행',
    actionCompleted: '사고 해결 및 보호 완료',
    showTelemetry: '원시 원격 측정 보기',
    hideTelemetry: '원격 측정 숨기기',
    dispatchedToWhatsApp: 'WhatsApp으로 전송됨',
    dispatchedTo: '수신자:',

    // Hero Card
    heroBadge: '쉬운 언어 레이더',
    heroTitle: '자율 WhatsApp 위협 파이프라인',
    heroSub: '이상 징후가 감지되면 엔진이 전문 용어 없는 모바일 알림을 생성하여 WhatsApp API를 통해 즉시 전송합니다.',
    heroActiveRecipient: '현재 수신자:',
    heroBtnTest: 'WhatsApp 전송 테스트',
    heroBtnSim: '시뮬레이터 실행',

    // General
    languageChangedToast: '언어가 다음으로 변경되었습니다:',
    saveChanges: '변경사항 저장',
    cancel: '취소',
    close: '닫기',
  },
  it: {
    // Nav & Brand
    aiRadar: 'Radar AI SaaS',
    radarActive: 'Radar Attivo',
    offline: 'Offline',
    searchPlaceholder: 'Cerca incidenti, anomalie, IP, utenti...',
    simulateAttack: 'Simula Attacco',
    notifications: 'Notifiche',
    liveNotifLog: 'Registro Notifiche in Tempo Reale',
    clearAll: 'Cancella tutto',
    noNotif: 'Nessuna nuova notifica',
    teamName: 'WolfPack Squadron',
    hackName: 'NexHack 2.0',
    selectLanguage: 'Seleziona Lingua',
    searchLanguage: 'Cerca lingua o paese...',
    indianLanguages: 'Lingue Indiane',
    internationalLanguages: 'Internazionale',

    // Sidebar
    navDashboard: 'Dashboard',
    navThreatAlerts: 'Radar Minacce',
    navTraffic: 'Analisi del Traffico',
    navWhatsApp: 'Invio WhatsApp',
    navSimulator: 'Simulatore di Attacco',
    navAuditLogs: 'Registri di Controllo',
    navSettings: 'Impostazioni Motore',

    // Metrics Grid
    metricTotalEvents: 'Eventi Totali Acquisiti',
    metricEventsSub: 'Telemetria a finestra scorrevole in tempo reale',
    metricAnomalies: 'Anomalie Rilevate',
    metricAnomaliesSub: 'Trigger euristici e picchi',
    metricThreatLevel: 'Livello di Minaccia Attivo',
    metricThreatLevelSub: 'Valutazione dinamica della baseline',
    metricWhatsApp: 'Invii Autonomi WhatsApp',
    metricWhatsAppSub: 'Avvisi chiari e senza gergo trasmessi',
    statusNominal: 'Telemetria Nominale',
    statusIncidents: 'Incidenti Critici',
    statusStrict: 'Scudo Rigoroso',
    statusDispatched: 'Avvisi Istantanei',

    // Traffic Chart
    chartTitle: 'Acquisizione Telemetria in Tempo Reale vs Picchi di Anomalie',
    chartSub: 'Volume di eventi con picchi di anomalie euristiche',
    chartLegendIngestion: 'Acquisizione (eps)',
    chartLegendAnomalies: 'Anomalie (conteggio)',
    tab15m: '15 Minuti',
    tab1h: '1 Ora',
    tab24h: '24 Ore',
    filterAll: 'Tutto il Traffico',
    filterAnomalies: 'Solo Anomalie',
    statPeakRate: 'Tasso di Acquisizione di Picco',
    statAnomalyRate: 'Tasso di Anomalie in Tempo Reale',
    statWindow: 'Durata Finestra',
    statBaseline: 'Stato Baseline',
    baselineStable: 'STABILE (12s)',

    // Threat Feed
    feedTitle: 'Intelligence sulle Minacce in Tempo Reale e Sintesi Semplice',
    feedSub: 'Radar di telemetria con traduzione istantanea in linguaggio naturale',
    feedLiveActive: 'STREAMING LIVE ATTIVO',
    filterAllAlerts: 'Tutti gli Avvisi',
    filterActive: 'Attivi',
    filterCritical: 'Critici',
    filterResolved: 'Risolti',
    noAlertsFound: 'Nessun incidente trovato.',
    takeRemediation: 'Esegui Azione di Ripristino',
    actionCompleted: 'Incidente Risolto e Protetto',
    showTelemetry: 'Mostra Telemetria Grezza',
    hideTelemetry: 'Nascondi Telemetria',
    dispatchedToWhatsApp: 'Inviato su WhatsApp',
    dispatchedTo: 'Inviato a',

    // Hero Card
    heroBadge: 'RADAR SENZA GERGO',
    heroTitle: 'Pipeline Autonoma di Minacce WhatsApp',
    heroSub: 'Quando viene rilevata un\'anomalia, il motore crea avvisi mobili chiari e li invia istantaneamente agli operatori tramite API WhatsApp.',
    heroActiveRecipient: 'Destinatario Attivo:',
    heroBtnTest: 'Test Invio WhatsApp',
    heroBtnSim: 'Avvia Simulatore',

    // General
    languageChangedToast: 'Lingua cambiata in:',
    saveChanges: 'Salva Modifiche',
    cancel: 'Annulla',
    close: 'Chiudi',
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children, onLanguageChangeNotification }) {
  const [currentLang, setCurrentLang] = useState(() => {
    return localStorage.getItem('neurolock_language') || 'en';
  });

  const setLanguage = (langCode) => {
    if (!TRANSLATIONS[langCode] && !LANGUAGES.find(l => l.code === langCode)) return;
    setCurrentLang(langCode);
    localStorage.setItem('neurolock_language', langCode);
    
    const langObj = LANGUAGES.find(l => l.code === langCode);
    const toastMessage = `${t('languageChangedToast', 'Language changed to')} ${langObj ? `${langObj.flag} ${langObj.nativeName} (${langObj.name})` : langCode}`;
    
    // Dispatch custom event so app components can respond or show notification
    window.dispatchEvent(new CustomEvent('neurolock-language-changed', {
      detail: { langCode, langObj, toastMessage }
    }));

    if (onLanguageChangeNotification) {
      onLanguageChangeNotification({
        title: '🌐 Language Updated / भाषा बदली',
        message: toastMessage,
        type: 'INFO',
        timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
      });
    }
  };

  const t = (key, fallback = '') => {
    const langDict = TRANSLATIONS[currentLang] || TRANSLATIONS['en'];
    if (langDict && langDict[key]) {
      return langDict[key];
    }
    const fallbackDict = TRANSLATIONS['en'];
    if (fallbackDict && fallbackDict[key]) {
      return fallbackDict[key];
    }
    return fallback || key;
  };

  const currentLangMeta = LANGUAGES.find(l => l.code === currentLang) || LANGUAGES[12]; // default English

  return (
    <LanguageContext.Provider value={{ currentLang, setLanguage, currentLangMeta, t, LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    // Fallback if not inside provider
    return {
      currentLang: 'en',
      setLanguage: () => {},
      currentLangMeta: LANGUAGES[12],
      t: (key, fallback = '') => fallback || key,
      LANGUAGES
    };
  }
  return context;
}
